# -*- coding: utf-8 -*-
"""Guías #3: valor fiscal (tablas de Hacienda) y tasación de un barco, 4 idiomas.
Fuente fiscal verificada: Orden HAC/1501/2025, de 17 de diciembre (BOE-A-2025-26357), art. 4 y anexos II y III."""
from content_cuanto_vale import aside

BOE = 'https://www.boe.es/buscar/act.php?id=BOE-A-2025-26357'

def faq_html(t, faq):
    return '<h2 id="faq">%s</h2>' % t + ''.join('<h3>%s</h3><p>%s</p>' % qa for qa in faq)

# ---------------------------------------------------------------- VALOR FISCAL
VF = {}
VF['es'] = dict(
 title='Valor fiscal de un barco: las tablas de Hacienda y cómo se calcula', h1='Valor fiscal de un barco: las tablas de Hacienda y cómo se calcula',
 desc='Qué es el valor fiscal de una embarcación, cómo lo calcula Hacienda con los precios medios de 2026 (casco, motor y años de uso) y por qué no es lo que vale tu barco.',
 eyebrow='Guías · Papeles e impuestos', meta='<span>Por Juan Morante</span><span>Actualizado octubre 2026</span><span>5 min de lectura</span>',
 lead='Cuando compras un barco a un particular, el impuesto no siempre se calcula sobre lo que has pagado. Hacienda tiene sus propios precios medios, las famosas «tablas», y conviene saber cómo funcionan antes de firmar.',
 body='''<h2 id="que-es">Qué es el valor fiscal</h2><p>Es el valor que la Administración da a un barco para calcular impuestos. Sale de los precios medios de venta que el Ministerio de Hacienda aprueba cada año. Para 2026 están en la <a href="%s" target="_blank" rel="noopener">Orden HAC/1501/2025, de 17 de diciembre</a>, en vigor desde el 1 de enero de 2026.</p><p>Se usan para el Impuesto de Transmisiones Patrimoniales (ITP), para Sucesiones y Donaciones y para el Impuesto Especial sobre Determinados Medios de Transporte (el de matriculación).</p>
<h2 id="calculo">Cómo se calcula</h2><p>La Orden valora por separado el casco sin motor y la motorización, y luego suma las dos partes:</p><ul><li><strong>Casco.</strong> Se parte del valor que figura para ese modelo en el anexo II de la Orden.</li><li><strong>Motor.</strong> Se parte de un valor base por unidad de potencia, que fija el anexo III.</li><li><strong>Años de uso.</strong> A cada parte se le aplica un porcentaje según los años de utilización, con la tabla del anexo III: cuanto más antiguo, menor porcentaje.</li><li><strong>Motos de agua.</strong> Se valoran de forma conjunta, sin separar casco y motor, según su potencia y sus años.</li></ul><p>Por eso un mismo barco puede tener un valor fiscal distinto según el motor que lleve.</p>
<h2 id="cuando">Cuándo te afecta</h2><p>Sobre todo al comprar un barco usado a un particular. En ese caso se paga el ITP en la comunidad del comprador (en Cataluña, el 5 %%), y la base es, en general, el mayor entre el precio que declaras y el valor de las tablas. Lo tienes por comunidades en la <a href="{P}/guias/itp-comprar-barco-usado-por-comunidad.html">guía del ITP al comprar un barco usado</a>, y puedes hacer números con la <a href="{P}/herramientas/impuestos-comprar-barco.html">calculadora de impuestos</a>.</p><p>Si compras a una empresa que vende con IVA, normalmente no hay ITP. Y en una herencia o donación, el valor fiscal también sirve de referencia.</p>
<h2 id="mercado">Valor fiscal no es valor de mercado</h2><p>Las tablas son medias: no miran el estado del barco, las horas del motor, la electrónica ni si ha tenido un mantenimiento impecable o ninguno. Un barco muy cuidado puede venderse por encima del valor fiscal, y uno con trabajos pendientes, por debajo.</p><p>Si declaras un precio por debajo de las tablas porque el barco está realmente peor, guarda pruebas (un peritaje, fotos, presupuestos de reparación): la Administración puede comprobar el valor y pedir la diferencia. Para saber lo que vale de verdad en el mercado, usa la <a href="{P}/cuanto-vale-mi-barco/">calculadora de cuánto vale mi barco</a>.</p>
<h2 id="tablas">Las «tablas de valoración» que circulan por internet</h2><p>En foros y webs circulan tablas de depreciación de barcos usados que no siempre son las vigentes. La única referencia oficial para impuestos es la Orden del año en curso publicada en el BOE. Si te pasan una tabla, comprueba de qué año es.</p>''' % BOE,
 faq_t='Preguntas frecuentes', faq=[
  ('¿Dónde consulto el valor fiscal de mi barco?', 'En los anexos de la Orden de precios medios del año en curso, publicada en el BOE. Algunas comunidades tienen además su propio buscador. Si tienes dudas con un modelo concreto, tu gestoría lo calcula en un momento.'),
  ('¿Pago el ITP sobre lo que he pagado o sobre las tablas?', 'En general, sobre el mayor de los dos. Si pagas más que el valor de tablas, sobre lo que has pagado; si pagas menos, la Administración puede tomar el valor de tablas.'),
  ('¿El valor fiscal sirve para poner precio a mi barco?', 'No. Sirve para impuestos. El precio de venta lo marca el mercado: lo que se está pidiendo y vendiendo por barcos parecidos en estado parecido.')],
 aviso='Información orientativa, revisada en octubre de 2026 a partir de la Orden HAC/1501/2025 (BOE-A-2025-26357). La normativa y los tipos pueden cambiar y cada comunidad autónoma tiene sus reglas: confirma tu caso con tu gestoría o con Hacienda antes de comprar o vender. Podemos equivocarnos y nada de esta página es vinculante.',
 a=('¿Compras o vendes?', 'Te ayudo a que los números cuadren.', 'Cuéntame la operación y te digo qué papeles e impuestos conviene mirar. Sin compromiso.', 'Hola Juan, tengo una duda sobre el valor fiscal de un barco.', 'Hablar con Juan por WhatsApp',
    'En esta guía', [('que-es', 'Qué es el valor fiscal'), ('calculo', 'Cómo se calcula'), ('cuando', 'Cuándo te afecta'), ('mercado', 'Valor fiscal no es valor de mercado'), ('tablas', 'Tablas que circulan por internet'), ('faq', 'Preguntas frecuentes')],
    'Otras guías', [('{P}/cuanto-vale-mi-barco/', '¿Cuánto vale mi barco?'), ('{P}/guias/itp-comprar-barco-usado-por-comunidad.html', 'ITP por comunidad autónoma'), ('{P}/guias/', 'Todas las guías')]),
 crumbs=[('Guías', 'guias/')])
VF['ca'] = dict(
 title="Valor fiscal d'un vaixell: les taules d'Hisenda i com es calcula", h1="Valor fiscal d'un vaixell: les taules d'Hisenda i com es calcula",
 desc="Què és el valor fiscal d'una embarcació, com el calcula Hisenda amb els preus mitjans del 2026 (buc, motor i anys d'ús) i per què no és el que val el teu vaixell.",
 eyebrow='Guies · Papers i impostos', meta="<span>Per Juan Morante</span><span>Actualitzat l'octubre de 2026</span><span>5 min de lectura</span>",
 lead="Quan compres un vaixell a un particular, l'impost no sempre es calcula sobre el que has pagat. Hisenda té els seus propis preus mitjans, les famoses «taules», i convé saber com funcionen abans de signar.",
 body='''<h2 id="que-es">Què és el valor fiscal</h2><p>És el valor que l'Administració dona a un vaixell per calcular impostos. Surt dels preus mitjans de venda que el Ministeri d'Hisenda aprova cada any. Per al 2026 són a l'<a href="%s" target="_blank" rel="noopener">Ordre HAC/1501/2025, de 17 de desembre</a>, vigent des de l'1 de gener de 2026.</p><p>S'utilitzen per a l'Impost de Transmissions Patrimonials (ITP), per a Successions i Donacions i per a l'Impost Especial sobre Determinats Mitjans de Transport (el de matriculació).</p>
<h2 id="calculo">Com es calcula</h2><p>L'Ordre valora per separat el buc sense motor i la motorització, i després suma les dues parts:</p><ul><li><strong>Buc.</strong> Es parteix del valor que figura per a aquest model a l'annex II de l'Ordre.</li><li><strong>Motor.</strong> Es parteix d'un valor base per unitat de potència, que fixa l'annex III.</li><li><strong>Anys d'ús.</strong> A cada part s'hi aplica un percentatge segons els anys d'utilització, amb la taula de l'annex III: com més antic, menor percentatge.</li><li><strong>Motos d'aigua.</strong> Es valoren de manera conjunta, sense separar buc i motor, segons la potència i els anys.</li></ul><p>Per això un mateix vaixell pot tenir un valor fiscal diferent segons el motor que porti.</p>
<h2 id="cuando">Quan t'afecta</h2><p>Sobretot quan compres un vaixell usat a un particular. En aquest cas es paga l'ITP a la comunitat del comprador (a Catalunya, el 5 %%), i la base és, en general, el més alt entre el preu que declares i el valor de les taules. Ho tens per comunitats a la <a href="{P}/guias/itp-comprar-barco-usado-por-comunidad.html">guia de l'ITP en comprar un vaixell usat</a>, i pots fer números amb la <a href="{P}/herramientas/impuestos-comprar-barco.html">calculadora d'impostos</a>.</p><p>Si compres a una empresa que ven amb IVA, normalment no hi ha ITP. I en una herència o donació, el valor fiscal també serveix de referència.</p>
<h2 id="mercado">Valor fiscal no és valor de mercat</h2><p>Les taules són mitjanes: no miren l'estat del vaixell, les hores del motor, l'electrònica ni si ha tingut un manteniment impecable o cap. Un vaixell molt cuidat es pot vendre per sobre del valor fiscal, i un amb feines pendents, per sota.</p><p>Si declares un preu per sota de les taules perquè el vaixell està realment pitjor, guarda proves (un peritatge, fotos, pressupostos de reparació): l'Administració pot comprovar el valor i demanar la diferència. Per saber el que val de veritat al mercat, fes servir la <a href="{P}/cuanto-vale-mi-barco/">calculadora de quant val el meu vaixell</a>.</p>
<h2 id="tablas">Les «taules de valoració» que circulen per internet</h2><p>En fòrums i webs circulen taules de depreciació de vaixells usats que no sempre són les vigents. L'única referència oficial per a impostos és l'Ordre de l'any en curs publicada al BOE. Si et passen una taula, comprova de quin any és.</p>''' % BOE,
 faq_t='Preguntes freqüents', faq=[
  ('On consulto el valor fiscal del meu vaixell?', "Als annexos de l'Ordre de preus mitjans de l'any en curs, publicada al BOE. Algunes comunitats tenen a més el seu propi cercador. Si tens dubtes amb un model concret, la teva gestoria el calcula en un moment."),
  ("Pago l'ITP sobre el que he pagat o sobre les taules?", "En general, sobre el més alt dels dos. Si pagues més que el valor de taules, sobre el que has pagat; si pagues menys, l'Administració pot agafar el valor de taules."),
  ('El valor fiscal serveix per posar preu al meu vaixell?', 'No. Serveix per a impostos. El preu de venda el marca el mercat: el que es demana i es ven per vaixells semblants en un estat semblant.')],
 aviso="Informació orientativa, revisada l'octubre de 2026 a partir de l'Ordre HAC/1501/2025 (BOE-A-2025-26357). La normativa i els tipus poden canviar i cada comunitat autònoma té les seves regles: confirma el teu cas amb la gestoria o amb Hisenda abans de comprar o vendre. Ens podem equivocar i res d'aquesta pàgina és vinculant.",
 a=('Compres o vens?', 'Et ajudo que els números quadrin.', "Explica'm l'operació i et dic quins papers i impostos convé mirar. Sense compromís.", "Hola Juan, tinc un dubte sobre el valor fiscal d'un vaixell.", 'Parlar amb Juan per WhatsApp',
    'En aquesta guia', [('que-es', 'Què és el valor fiscal'), ('calculo', 'Com es calcula'), ('cuando', "Quan t'afecta"), ('mercado', 'Valor fiscal no és valor de mercat'), ('tablas', 'Taules que circulen per internet'), ('faq', 'Preguntes freqüents')],
    'Altres guies', [('{P}/cuanto-vale-mi-barco/', 'Quant val el meu vaixell?'), ('{P}/guias/itp-comprar-barco-usado-por-comunidad.html', 'ITP per comunitat autònoma'), ('{P}/guias/', 'Totes les guies')]),
 crumbs=[('Guies', 'guias/')])
VF['en'] = dict(
 title='Tax value of a boat in Spain: the official tables and how it is calculated', h1='Tax value of a boat in Spain: the official tables and how it is calculated',
 desc="What a boat's tax value is in Spain, how the tax authorities calculate it with the 2026 average prices (hull, engine and years of use) and why it is not what your boat is worth.",
 eyebrow='Guides · Paperwork and taxes', meta='<span>By Juan Morante</span><span>Updated October 2026</span><span>5 min read</span>',
 lead="When you buy a boat from a private seller in Spain, the tax isn't always calculated on what you paid. The tax authorities have their own average prices, the so-called “tables”, and it is worth knowing how they work before you sign.",
 body='''<h2 id="que-es">What the tax value is</h2><p>It is the value the authorities give a boat in order to calculate taxes. It comes from the average sale prices approved every year by the Spanish Ministry of Finance. For 2026 they are in <a href="%s" target="_blank" rel="noopener">Order HAC/1501/2025 of 17 December</a>, in force since 1 January 2026.</p><p>They are used for transfer tax (ITP), inheritance and gift tax, and the special registration tax on certain means of transport.</p>
<h2 id="calculo">How it is calculated</h2><p>The Order values the hull without engine and the engines separately, then adds the two together:</p><ul><li><strong>Hull.</strong> The starting point is the value listed for that model in Annex II of the Order.</li><li><strong>Engine.</strong> The starting point is a base value per unit of power, set in Annex III.</li><li><strong>Years of use.</strong> Each part is multiplied by a percentage based on its years of use, using the table in Annex III: the older it is, the lower the percentage.</li><li><strong>Jet skis.</strong> They are valued as a single unit, without separating hull and engine, according to their power and age.</li></ul><p>That is why the same boat can have a different tax value depending on the engine it carries.</p>
<h2 id="cuando">When it affects you</h2><p>Mainly when you buy a used boat from a private seller. In that case transfer tax is paid in the buyer\'s region (5%% in Catalonia), and the taxable base is generally the higher of the declared price and the table value. You can see it by region in the <a href="{P}/guias/itp-comprar-barco-usado-por-comunidad.html">guide to transfer tax on a used boat</a>, and run the numbers with the <a href="{P}/herramientas/impuestos-comprar-barco.html">tax calculator</a>.</p><p>If you buy from a company that sells with VAT, there is normally no transfer tax. In an inheritance or gift, the tax value is also used as a reference.</p>
<h2 id="mercado">Tax value is not market value</h2><p>The tables are averages: they ignore the boat\'s condition, engine hours, electronics and whether it has been impeccably maintained or not at all. A very well kept boat can sell above its tax value, and one that needs work, below it.</p><p>If you declare a price below the tables because the boat really is in worse condition, keep evidence (a survey, photos, repair quotes): the authorities can review the value and claim the difference. To find out what it is really worth on the market, use the <a href="{P}/cuanto-vale-mi-barco/">how much is my boat worth calculator</a>.</p>
<h2 id="tablas">The “valuation tables” found online</h2><p>Forums and websites share depreciation tables for used boats that are not always the current ones. The only official reference for tax purposes is the current year\'s Order published in the BOE (Spain\'s Official Gazette). If someone sends you a table, check which year it is from.</p>''' % BOE,
 faq_t='Frequently asked questions', faq=[
  ("Where can I check my boat's tax value?", "In the annexes of the current year's average price Order, published in the BOE. Some regions also have their own search tool. If you are unsure about a particular model, a gestoría (administrative agent) can work it out in no time."),
  ('Do I pay transfer tax on what I paid or on the tables?', 'Generally on the higher of the two. If you pay more than the table value, on what you paid; if you pay less, the authorities may use the table value.'),
  ('Can I use the tax value to price my boat?', "No. It is for taxes. The selling price is set by the market: what similar boats in similar condition are being listed and sold for.")],
 aviso='For guidance only, reviewed in October 2026 based on Order HAC/1501/2025 (BOE-A-2025-26357). Rules and rates may change and each Spanish region has its own: confirm your case with a gestoría or the tax office before buying or selling. We may be wrong and nothing on this page is binding.',
 a=('Buying or selling?', "I'll help make the numbers add up.", "Tell me about the deal and I'll point out which paperwork and taxes to look at. No obligation.", "Hi Juan, I have a question about a boat's tax value.", 'Talk to Juan on WhatsApp',
    'In this guide', [('que-es', 'What the tax value is'), ('calculo', 'How it is calculated'), ('cuando', 'When it affects you'), ('mercado', 'Tax value is not market value'), ('tablas', 'Tables found online'), ('faq', 'FAQ')],
    'Other guides', [('{P}/cuanto-vale-mi-barco/', 'How much is my boat worth?'), ('{P}/guias/itp-comprar-barco-usado-por-comunidad.html', 'Transfer tax by region'), ('{P}/guias/', 'All guides')]),
 crumbs=[('Guides', 'guias/')])
VF['fr'] = dict(
 title="Valeur fiscale d'un bateau en Espagne : les barèmes officiels et leur calcul", h1="Valeur fiscale d'un bateau en Espagne : les barèmes officiels et leur calcul",
 desc="Ce qu'est la valeur fiscale d'un bateau en Espagne, comment le fisc la calcule avec les prix moyens 2026 (coque, moteur et années d'utilisation) et pourquoi ce n'est pas ce que vaut votre bateau.",
 eyebrow='Guides · Papiers et fiscalité', meta='<span>Par Juan Morante</span><span>Mis à jour en octobre 2026</span><span>5 min de lecture</span>',
 lead="Quand vous achetez un bateau à un particulier en Espagne, l'impôt n'est pas toujours calculé sur le prix payé. Le fisc espagnol a ses propres prix moyens, les fameux « barèmes », et mieux vaut savoir comment ils fonctionnent avant de signer.",
 body='''<h2 id="que-es">Qu'est-ce que la valeur fiscale</h2><p>C'est la valeur que l'administration attribue à un bateau pour calculer les impôts. Elle provient des prix moyens de vente approuvés chaque année par le ministère espagnol des Finances. Pour 2026, ils figurent dans l'<a href="%s" target="_blank" rel="noopener">Ordre HAC/1501/2025 du 17 décembre</a>, en vigueur depuis le 1er janvier 2026.</p><p>Ils servent pour l'ITP (droits de mutation), les droits de succession et de donation et la taxe spéciale d'immatriculation sur certains moyens de transport.</p>
<h2 id="calculo">Comment elle est calculée</h2><p>L'Ordre évalue séparément la coque sans moteur et la motorisation, puis additionne les deux :</p><ul><li><strong>Coque.</strong> On part de la valeur indiquée pour ce modèle à l'annexe II de l'Ordre.</li><li><strong>Moteur.</strong> On part d'une valeur de base par unité de puissance, fixée à l'annexe III.</li><li><strong>Années d'utilisation.</strong> On applique à chaque partie un pourcentage selon les années d'utilisation, d'après le tableau de l'annexe III : plus il est ancien, plus le pourcentage est bas.</li><li><strong>Scooters des mers.</strong> Ils sont évalués comme un tout, sans séparer coque et moteur, selon leur puissance et leur âge.</li></ul><p>C'est pourquoi un même bateau peut avoir une valeur fiscale différente selon le moteur qu'il porte.</p>
<h2 id="cuando">Quand cela vous concerne</h2><p>Surtout lorsque vous achetez un bateau d'occasion à un particulier. L'ITP est alors payé dans la communauté autonome de l'acheteur (5 %% en Catalogne), et la base est en général la plus élevée entre le prix déclaré et la valeur du barème. Vous trouverez le détail par région dans le <a href="{P}/guias/itp-comprar-barco-usado-por-comunidad.html">guide de l'ITP pour un bateau d'occasion</a>, et vous pouvez faire vos calculs avec le <a href="{P}/herramientas/impuestos-comprar-barco.html">calculateur d'impôts</a>.</p><p>Si vous achetez à une entreprise qui vend avec TVA, il n'y a normalement pas d'ITP. Pour une succession ou une donation, la valeur fiscale sert aussi de référence.</p><p>Si vous comptez ramener le bateau en France, lisez aussi le guide <a href="{P}/guias/comprar-barco-espana-matricular-francia.html">acheter un bateau en Espagne et l'immatriculer en France</a>.</p>
<h2 id="mercado">Valeur fiscale n'est pas valeur de marché</h2><p>Les barèmes sont des moyennes : ils ne tiennent compte ni de l'état du bateau, ni des heures moteur, ni de l'électronique, ni de la qualité de l'entretien. Un bateau très soigné peut se vendre au-dessus de sa valeur fiscale, et un bateau avec des travaux à prévoir, en dessous.</p><p>Si vous déclarez un prix inférieur au barème parce que le bateau est réellement en moins bon état, gardez des preuves (une expertise, des photos, des devis de réparation) : l'administration peut vérifier la valeur et réclamer la différence. Pour connaître sa vraie valeur sur le marché, utilisez le <a href="{P}/cuanto-vale-mi-barco/">calculateur « combien vaut mon bateau »</a>.</p>
<h2 id="tablas">Les « barèmes de valeur » qui circulent sur internet</h2><p>Sur les forums et certains sites circulent des tableaux de dépréciation de bateaux d'occasion qui ne sont pas toujours ceux en vigueur. La seule référence officielle pour l'impôt est l'Ordre de l'année en cours publié au BOE (Journal officiel espagnol). Si on vous transmet un barème, vérifiez de quelle année il date.</p>''' % BOE,
 faq_t='Questions fréquentes', faq=[
  ('Où consulter la valeur fiscale de mon bateau ?', "Dans les annexes de l'Ordre des prix moyens de l'année en cours, publié au BOE. Certaines communautés autonomes proposent aussi leur propre outil de recherche. En cas de doute sur un modèle précis, une gestoría (cabinet administratif) la calcule en un instant."),
  ("Je paie l'ITP sur le prix payé ou sur le barème ?", "En général, sur le plus élevé des deux. Si vous payez plus que la valeur du barème, sur le prix payé ; si vous payez moins, l'administration peut retenir la valeur du barème."),
  ('La valeur fiscale sert-elle à fixer le prix de mon bateau ?', "Non. Elle sert pour l'impôt. Le prix de vente est fixé par le marché : ce qui est demandé et vendu pour des bateaux similaires dans un état similaire.")],
 aviso="Information indicative, revue en octobre 2026 sur la base de l'Ordre HAC/1501/2025 (BOE-A-2025-26357). Les règles et les taux peuvent changer et chaque communauté autonome a les siennes : confirmez votre cas auprès d'une gestoría ou du fisc avant d'acheter ou de vendre. Nous pouvons nous tromper et rien sur cette page n'est contractuel.",
 a=('Vous achetez ou vous vendez ?', 'Je vous aide à faire les bons calculs.', "Expliquez-moi l'opération et je vous dis quels papiers et impôts regarder. Sans engagement.", "Bonjour Juan, j'ai une question sur la valeur fiscale d'un bateau.", 'Parler à Juan sur WhatsApp',
    'Dans ce guide', [('que-es', "Qu'est-ce que la valeur fiscale"), ('calculo', 'Comment elle est calculée'), ('cuando', 'Quand cela vous concerne'), ('mercado', "Valeur fiscale n'est pas valeur de marché"), ('tablas', 'Barèmes sur internet'), ('faq', 'Questions fréquentes')],
    'Autres guides', [('{P}/cuanto-vale-mi-barco/', 'Combien vaut mon bateau ?'), ('{P}/guias/itp-comprar-barco-usado-por-comunidad.html', "L'ITP par région"), ('{P}/guias/', 'Tous les guides')]),
 crumbs=[('Guides', 'guias/')])

# ---------------------------------------------------------------- TASACIÓN
TS = {}
TS['es'] = dict(
 title='Tasación de un barco: valoración, peritaje y cuándo necesitas cada uno', h1='Tasación de un barco: valoración, peritaje y cuándo necesitas cada uno',
 desc='Diferencia entre valorar, peritar y tasar un barco usado, quién lo hace, qué revisa un perito y cuándo te hace falta cada uno al comprar, vender, asegurar o heredar.',
 eyebrow='Guías · Comprar y vender', meta='<span>Por Juan Morante</span><span>Actualizado octubre 2026</span><span>5 min de lectura</span>',
 lead='«Tasar un barco» se usa para tres cosas distintas: saber cuánto pedir, saber en qué estado está y tener un informe que valga ante un banco, una aseguradora o un juzgado. Confundirlas sale caro, así que aquí van por separado.',
 body='''<h2 id="tres">Tres cosas que se confunden</h2><ul><li><strong>Valoración de mercado.</strong> Responde a «¿cuánto puedo pedir o pagar?». Se hace comparando con barcos parecidos que se anuncian y se venden. Es lo que te da un broker o la <a href="{P}/cuanto-vale-mi-barco/">calculadora de cuánto vale mi barco</a>.</li><li><strong>Peritaje o inspección (survey).</strong> Responde a «¿cómo está de verdad?». Un perito revisa el barco, normalmente en seco y con prueba de mar, y te entrega un informe de estado.</li><li><strong>Tasación formal.</strong> Un informe firmado por un perito que fija un valor y que sirve ante terceros: financiación, seguro, herencia, reparto de bienes o un pleito.</li></ul>
<h2 id="cuando">Cuándo necesitas cada una</h2><ul><li><strong>Vas a vender.</strong> Con una valoración de mercado bien hecha suele bastar para fijar el precio de salida.</li><li><strong>Vas a comprar.</strong> El peritaje es lo que más te protege, sobre todo en barcos grandes o con motores intraborda. Hazlo antes de pagar o deja las arras condicionadas a su resultado; te lo explico en la <a href="{P}/guias/arras-compraventa-barco.html">guía de arras</a>.</li><li><strong>Financias o aseguras.</strong> Algunos bancos y aseguradoras piden una tasación o un informe de estado, sobre todo en barcos con años. Pregunta antes qué formato aceptan.</li><li><strong>Herencia, donación o divorcio.</strong> Para impuestos se usa el <a href="{P}/guias/valor-fiscal-barco-tablas-hacienda.html">valor fiscal de las tablas de Hacienda</a>; si el barco vale claramente menos, una tasación pericial ayuda a justificarlo.</li></ul>
<h2 id="quien">Quién la hace</h2><p>Un perito naval o surveyor independiente. Para comprar, lo importante es que no cobre de la venta: ni el vendedor ni quien intermedia deberían elegir por ti al perito. Pide antes qué va a revisar, si incluye prueba de mar y varada, y en cuánto tiempo entrega el informe.</p>
<h2 id="revisa">Qué revisa un buen peritaje</h2><ul><li>Casco y cubierta: golpes, reparaciones, grietas en el gelcoat y humedad en el laminado (con medidor).</li><li>Motores y transmisión: horas, fugas, refrigeración, colas o ejes, y a ser posible un análisis de aceite.</li><li>Instalación eléctrica, gas, combustible, achique y válvulas de fondo.</li><li>Jarcia y velas, si es un velero.</li><li>Equipo de seguridad y documentación: que lo que dicen los papeles coincide con el barco.</li></ul>
<h2 id="online">Las tasaciones online</h2><p>Las calculadoras online, incluida la mía, sirven para orientarse: dicen en qué rango se anuncian barcos parecidos. No ven tu barco, así que no sustituyen a un peritaje antes de comprar ni a una tasación cuando alguien te la exige.</p>''',
 faq_t='Preguntas frecuentes', faq=[
  ('¿Es obligatorio peritar un barco usado antes de comprarlo?', 'No es obligatorio, pero es lo más recomendable, sobre todo si el barco tiene años, motores intraborda o un precio alto. Un problema oculto suele costar bastante más que el peritaje.'),
  ('¿Quién paga el peritaje?', 'Lo habitual es que lo pague quien lo encarga, normalmente el comprador. Si lo pide el banco o la aseguradora, también suele pagarlo el cliente.'),
  ('¿Me sirve la valoración de un broker como tasación?', 'Te sirve para poner o negociar el precio. Si un banco, una aseguradora o un juzgado piden una tasación, necesitarás un informe firmado por un perito.')],
 aviso='Información orientativa, revisada en octubre de 2026. No es asesoramiento técnico ni jurídico; cada caso depende del barco y de quién pide el informe. Podemos equivocarnos y nada de esta página es vinculante.',
 a=('¿Compras o vendes?', 'Te digo qué te hace falta en tu caso.', 'Cuéntame si compras o vendes y qué barco es, y te digo si te basta con una valoración o conviene peritar. Sin compromiso.', 'Hola Juan, tengo una duda sobre la tasación de un barco.', 'Hablar con Juan por WhatsApp',
    'En esta guía', [('tres', 'Tres cosas que se confunden'), ('cuando', 'Cuándo necesitas cada una'), ('quien', 'Quién la hace'), ('revisa', 'Qué revisa un buen peritaje'), ('online', 'Las tasaciones online'), ('faq', 'Preguntas frecuentes')],
    'Otras guías', [('{P}/cuanto-vale-mi-barco/', '¿Cuánto vale mi barco?'), ('{P}/guias/arras-compraventa-barco.html', 'Arras al comprar un barco'), ('{P}/guias/', 'Todas las guías')]),
 crumbs=[('Guías', 'guias/')])
TS['ca'] = dict(
 title="Taxació d'un vaixell: valoració, peritatge i quan necessites cadascun", h1="Taxació d'un vaixell: valoració, peritatge i quan necessites cadascun",
 desc="Diferència entre valorar, peritar i taxar un vaixell usat, qui ho fa, què revisa un perit i quan et cal cadascun en comprar, vendre, assegurar o heretar.",
 eyebrow='Guies · Comprar i vendre', meta="<span>Per Juan Morante</span><span>Actualitzat l'octubre de 2026</span><span>5 min de lectura</span>",
 lead="«Taxar un vaixell» es fa servir per a tres coses diferents: saber quant demanar, saber en quin estat està i tenir un informe que valgui davant d'un banc, una asseguradora o un jutjat. Confondre-les surt car, així que aquí van per separat.",
 body='''<h2 id="tres">Tres coses que es confonen</h2><ul><li><strong>Valoració de mercat.</strong> Respon a «quant puc demanar o pagar?». Es fa comparant amb vaixells semblants que s'anuncien i es venen. És el que et dona un broker o la <a href="{P}/cuanto-vale-mi-barco/">calculadora de quant val el meu vaixell</a>.</li><li><strong>Peritatge o inspecció (survey).</strong> Respon a «com està de veritat?». Un perit revisa el vaixell, normalment en sec i amb prova de mar, i t'entrega un informe d'estat.</li><li><strong>Taxació formal.</strong> Un informe signat per un perit que fixa un valor i que serveix davant de tercers: finançament, assegurança, herència, repartiment de béns o un plet.</li></ul>
<h2 id="cuando">Quan necessites cadascuna</h2><ul><li><strong>Vols vendre.</strong> Amb una valoració de mercat ben feta sol n'hi ha prou per fixar el preu de sortida.</li><li><strong>Vols comprar.</strong> El peritatge és el que més et protegeix, sobretot en vaixells grans o amb motors intrabord. Fes-lo abans de pagar o deixa les arres condicionades al resultat; t'ho explico a la <a href="{P}/guias/arras-compraventa-barco.html">guia d'arres</a>.</li><li><strong>Finances o assegures.</strong> Alguns bancs i asseguradores demanen una taxació o un informe d'estat, sobretot en vaixells amb anys. Pregunta abans quin format accepten.</li><li><strong>Herència, donació o divorci.</strong> Per a impostos es fa servir el <a href="{P}/guias/valor-fiscal-barco-tablas-hacienda.html">valor fiscal de les taules d'Hisenda</a>; si el vaixell val clarament menys, una taxació pericial ajuda a justificar-ho.</li></ul>
<h2 id="quien">Qui la fa</h2><p>Un perit naval o surveyor independent. Per comprar, l'important és que no cobri de la venda: ni el venedor ni qui fa d'intermediari haurien de triar per tu el perit. Demana abans què revisarà, si inclou prova de mar i varada, i en quant de temps lliura l'informe.</p>
<h2 id="revisa">Què revisa un bon peritatge</h2><ul><li>Buc i coberta: cops, reparacions, esquerdes al gelcoat i humitat al laminat (amb mesurador).</li><li>Motors i transmissió: hores, fuites, refrigeració, cues o eixos, i si pot ser una anàlisi d'oli.</li><li>Instal·lació elèctrica, gas, combustible, buidatge i vàlvules de fons.</li><li>Eixàrcia i veles, si és un veler.</li><li>Equip de seguretat i documentació: que el que diuen els papers coincideix amb el vaixell.</li></ul>
<h2 id="online">Les taxacions en línia</h2><p>Les calculadores en línia, inclosa la meva, serveixen per orientar-se: diuen en quin rang s'anuncien vaixells semblants. No veuen el teu vaixell, així que no substitueixen un peritatge abans de comprar ni una taxació quan algú te l'exigeix.</p>''',
 faq_t='Preguntes freqüents', faq=[
  ('És obligatori peritar un vaixell usat abans de comprar-lo?', "No és obligatori, però és el més recomanable, sobretot si el vaixell té anys, motors intrabord o un preu alt. Un problema ocult sol costar bastant més que el peritatge."),
  ('Qui paga el peritatge?', "L'habitual és que el pagui qui l'encarrega, normalment el comprador. Si el demana el banc o l'asseguradora, també sol pagar-lo el client."),
  ("Em serveix la valoració d'un broker com a taxació?", "Et serveix per posar o negociar el preu. Si un banc, una asseguradora o un jutjat demanen una taxació, necessitaràs un informe signat per un perit.")],
 aviso="Informació orientativa, revisada l'octubre de 2026. No és assessorament tècnic ni jurídic; cada cas depèn del vaixell i de qui demana l'informe. Ens podem equivocar i res d'aquesta pàgina és vinculant.",
 a=('Compres o vens?', 'Et dic què et cal en el teu cas.', "Explica'm si compres o vens i quin vaixell és, i et dic si n'hi ha prou amb una valoració o convé peritar. Sense compromís.", "Hola Juan, tinc un dubte sobre la taxació d'un vaixell.", 'Parlar amb Juan per WhatsApp',
    'En aquesta guia', [('tres', 'Tres coses que es confonen'), ('cuando', 'Quan necessites cadascuna'), ('quien', 'Qui la fa'), ('revisa', 'Què revisa un bon peritatge'), ('online', 'Les taxacions en línia'), ('faq', 'Preguntes freqüents')],
    'Altres guies', [('{P}/cuanto-vale-mi-barco/', 'Quant val el meu vaixell?'), ('{P}/guias/arras-compraventa-barco.html', 'Arres en comprar un vaixell'), ('{P}/guias/', 'Totes les guies')]),
 crumbs=[('Guies', 'guias/')])
TS['en'] = dict(
 title='Boat valuation and survey: what each one is and when you need it', h1='Boat valuation and survey: what each one is and when you need it',
 desc='The difference between a market valuation, a survey and a formal valuation of a used boat, who does them, what a surveyor checks and when you need each one.',
 eyebrow='Guides · Buying and selling', meta='<span>By Juan Morante</span><span>Updated October 2026</span><span>5 min read</span>',
 lead="“Valuing a boat” is used for three different things: knowing what to ask, knowing what condition it is in, and having a report that a bank, insurer or court will accept. Mixing them up can be costly, so here they are one by one.",
 body='''<h2 id="tres">Three things that get mixed up</h2><ul><li><strong>Market valuation.</strong> Answers “how much can I ask or pay?”. It is done by comparing with similar boats being listed and sold. It is what a broker gives you, or the <a href="{P}/cuanto-vale-mi-barco/">how much is my boat worth calculator</a>.</li><li><strong>Survey (inspection).</strong> Answers “what condition is it really in?”. A surveyor checks the boat, usually out of the water and with a sea trial, and gives you a condition report.</li><li><strong>Formal valuation.</strong> A report signed by a surveyor that sets a value and is accepted by third parties: finance, insurance, inheritance, division of assets or a court case.</li></ul>
<h2 id="cuando">When you need each one</h2><ul><li><strong>You are selling.</strong> A well-made market valuation is usually enough to set the asking price.</li><li><strong>You are buying.</strong> A survey is what protects you most, especially on larger boats or boats with inboard engines. Have it done before paying, or make the deposit conditional on the result; I explain it in the <a href="{P}/guias/arras-compraventa-barco.html">guide to deposits (arras)</a>.</li><li><strong>You are financing or insuring.</strong> Some banks and insurers ask for a valuation or condition report, especially on older boats. Ask first which format they accept.</li><li><strong>Inheritance, gift or divorce.</strong> For tax purposes the <a href="{P}/guias/valor-fiscal-barco-tablas-hacienda.html">tax value from the official tables</a> is used; if the boat is clearly worth less, a surveyor\'s valuation helps to justify it.</li></ul>
<h2 id="quien">Who does it</h2><p>An independent marine surveyor. When buying, the key point is that they are not paid out of the sale: neither the seller nor the intermediary should choose the surveyor for you. Ask beforehand what they will check, whether a sea trial and haul-out are included, and how long the report takes.</p>
<h2 id="revisa">What a good survey checks</h2><ul><li>Hull and deck: impacts, repairs, gelcoat cracks and moisture in the laminate (with a meter).</li><li>Engines and drivetrain: hours, leaks, cooling, sterndrives or shafts and, ideally, an oil analysis.</li><li>Electrical system, gas, fuel, bilge pumps and seacocks.</li><li>Rigging and sails, if it is a sailboat.</li><li>Safety equipment and paperwork: that what the documents say matches the boat.</li></ul>
<h2 id="online">Online valuations</h2><p>Online calculators, mine included, are useful to get your bearings: they tell you the range similar boats are listed at. They don\'t see your boat, so they don\'t replace a survey before buying, or a formal valuation when someone requires one.</p>''',
 faq_t='Frequently asked questions', faq=[
  ('Is a survey compulsory before buying a used boat?', "It isn't compulsory, but it is strongly advisable, especially if the boat is older, has inboard engines or a high price. A hidden problem usually costs far more than the survey."),
  ('Who pays for the survey?', 'Usually whoever commissions it, normally the buyer. If the bank or insurer asks for it, the customer usually pays as well.'),
  ("Can I use a broker's valuation as a formal valuation?", 'It is useful for setting or negotiating the price. If a bank, insurer or court asks for a formal valuation, you will need a report signed by a surveyor.')],
 aviso='For guidance only, reviewed in October 2026. This is not technical or legal advice; each case depends on the boat and on who is asking for the report. We may be wrong and nothing on this page is binding.',
 a=('Buying or selling?', "I'll tell you what you need in your case.", "Tell me whether you are buying or selling and which boat it is, and I'll tell you whether a valuation is enough or a survey is worth it. No obligation.", 'Hi Juan, I have a question about valuing a boat.', 'Talk to Juan on WhatsApp',
    'In this guide', [('tres', 'Three things that get mixed up'), ('cuando', 'When you need each one'), ('quien', 'Who does it'), ('revisa', 'What a good survey checks'), ('online', 'Online valuations'), ('faq', 'FAQ')],
    'Other guides', [('{P}/cuanto-vale-mi-barco/', 'How much is my boat worth?'), ('{P}/guias/arras-compraventa-barco.html', 'Deposits when buying a boat'), ('{P}/guias/', 'All guides')]),
 crumbs=[('Guides', 'guias/')])
TS['fr'] = dict(
 title="Expertise d'un bateau : estimation, inspection et quand il vous faut chacune", h1="Expertise d'un bateau : estimation, inspection et quand il vous faut chacune",
 desc="La différence entre estimer, inspecter et expertiser un bateau d'occasion, qui s'en charge, ce que vérifie un expert et quand il vous faut chacune pour acheter, vendre, assurer ou hériter.",
 eyebrow='Guides · Achat et vente', meta='<span>Par Juan Morante</span><span>Mis à jour en octobre 2026</span><span>5 min de lecture</span>',
 lead="« Expertiser un bateau » recouvre trois choses différentes : savoir combien en demander, savoir dans quel état il est, et disposer d'un rapport accepté par une banque, un assureur ou un tribunal. Les confondre coûte cher, alors les voici une par une.",
 body='''<h2 id="tres">Trois choses que l'on confond</h2><ul><li><strong>Estimation de marché.</strong> Répond à « combien puis-je demander ou payer ? ». Elle se fait en comparant avec des bateaux similaires annoncés et vendus. C'est ce que vous donne un broker, ou le <a href="{P}/cuanto-vale-mi-barco/">calculateur « combien vaut mon bateau »</a>.</li><li><strong>Inspection (survey).</strong> Répond à « dans quel état est-il vraiment ? ». Un expert examine le bateau, en général à sec et avec un essai en mer, et vous remet un rapport d'état.</li><li><strong>Expertise de valeur.</strong> Un rapport signé par un expert qui fixe une valeur et qui est accepté par des tiers : financement, assurance, succession, partage de biens ou litige.</li></ul>
<h2 id="cuando">Quand il vous faut chacune</h2><ul><li><strong>Vous vendez.</strong> Une estimation de marché bien faite suffit en général pour fixer le prix de départ.</li><li><strong>Vous achetez.</strong> L'inspection est ce qui vous protège le plus, surtout sur les grands bateaux ou ceux à moteurs in-bord. Faites-la avant de payer ou conditionnez les arrhes à son résultat ; je l'explique dans le <a href="{P}/guias/arras-compraventa-barco.html">guide des arrhes (arras)</a>.</li><li><strong>Vous financez ou assurez.</strong> Certaines banques et compagnies d'assurance demandent une expertise ou un rapport d'état, surtout pour les bateaux anciens. Demandez d'abord quel format elles acceptent.</li><li><strong>Succession, donation ou divorce.</strong> Pour l'impôt, c'est la <a href="{P}/guias/valor-fiscal-barco-tablas-hacienda.html">valeur fiscale des barèmes officiels</a> qui s'applique ; si le bateau vaut nettement moins, une expertise aide à le justifier.</li></ul>
<h2 id="quien">Qui s'en charge</h2><p>Un expert maritime indépendant (surveyor). À l'achat, l'essentiel est qu'il ne soit pas rémunéré sur la vente : ni le vendeur ni l'intermédiaire ne devraient choisir l'expert à votre place. Demandez avant ce qu'il va vérifier, si l'essai en mer et la mise à sec sont inclus, et sous quel délai il remet le rapport.</p>
<h2 id="revisa">Ce que vérifie une bonne inspection</h2><ul><li>Coque et pont : chocs, réparations, fissures du gelcoat et humidité du stratifié (avec un humidimètre).</li><li>Moteurs et transmission : heures, fuites, refroidissement, embases ou lignes d'arbre et, si possible, une analyse d'huile.</li><li>Installation électrique, gaz, carburant, pompes de cale et vannes.</li><li>Gréement et voiles, s'il s'agit d'un voilier.</li><li>Équipement de sécurité et papiers : que ce qui figure sur les documents correspond bien au bateau.</li></ul>
<h2 id="online">Les estimations en ligne</h2><p>Les calculateurs en ligne, y compris le mien, servent à se repérer : ils indiquent dans quelle fourchette sont annoncés des bateaux similaires. Ils ne voient pas votre bateau, donc ils ne remplacent ni une inspection avant l'achat, ni une expertise quand on vous en demande une.</p>''',
 faq_t='Questions fréquentes', faq=[
  ("L'inspection est-elle obligatoire avant d'acheter un bateau d'occasion ?", "Elle n'est pas obligatoire, mais c'est vivement recommandé, surtout si le bateau est ancien, a des moteurs in-bord ou un prix élevé. Un vice caché coûte en général bien plus cher que l'inspection."),
  ("Qui paie l'inspection ?", "En général, celui qui la commande, le plus souvent l'acheteur. Si c'est la banque ou l'assureur qui la demande, c'est aussi le client qui paie d'habitude."),
  ("L'estimation d'un broker vaut-elle expertise ?", "Elle sert à fixer ou négocier le prix. Si une banque, un assureur ou un tribunal demande une expertise, il vous faudra un rapport signé par un expert.")],
 aviso="Information indicative, revue en octobre 2026. Ceci n'est pas un conseil technique ni juridique ; chaque cas dépend du bateau et de qui demande le rapport. Nous pouvons nous tromper et rien sur cette page n'est contractuel.",
 a=('Vous achetez ou vous vendez ?', 'Je vous dis ce qu’il vous faut dans votre cas.', "Dites-moi si vous achetez ou vendez et de quel bateau il s'agit, et je vous dis si une estimation suffit ou s'il vaut mieux une inspection. Sans engagement.", "Bonjour Juan, j'ai une question sur l'expertise d'un bateau.", 'Parler à Juan sur WhatsApp',
    'Dans ce guide', [('tres', "Trois choses que l'on confond"), ('cuando', 'Quand il vous faut chacune'), ('quien', "Qui s'en charge"), ('revisa', 'Ce que vérifie une bonne inspection'), ('online', 'Les estimations en ligne'), ('faq', 'Questions fréquentes')],
    'Autres guides', [('{P}/cuanto-vale-mi-barco/', 'Combien vaut mon bateau ?'), ('{P}/guias/arras-compraventa-barco.html', "Les arrhes à l'achat d'un bateau"), ('{P}/guias/', 'Tous les guides')]),
 crumbs=[('Guides', 'guias/')])

def pages(D):
    out, crumbs = {}, {}
    for l, b in D.items():
        body = b['body'] + '\n' + faq_html(b['faq_t'], b['faq'])
        out[l] = dict(title=b['title'], h1=b['h1'], desc=b['desc'], eyebrow=b['eyebrow'], meta=b['meta'], lead=b['lead'], body=body,
                      aviso=b['aviso'], aside=aside(*b['a']), faq=b['faq'])
        crumbs[l] = b['crumbs']
    return out, crumbs
