# -*- coding: utf-8 -*-
# Llaüts y guía "¿Cuánto cuesta un barco?" (ES/CA/EN/FR). {P} = prefijo de idioma.
PAGES = {}

PAGES['llauts-segunda-mano'] = {
 'filter': {"types": ["llaut"]},
 'es': {
  'title': 'Llaüts de segunda mano en venta: qué mirar y precios',
  'desc': 'Llaüts de ocasión en Cataluña y Baleares: madera o fibra, qué revisar (calafateo, quilla, motor), título necesario y cómo encontrar uno. Te aviso cuando entre.',
  'eyebrow': 'Comprar barco · Llaüts',
  'h1': 'Llaüts de segunda mano',
  'lead': 'El llaüt es el barco de toda la vida del Mediterráneo: noble, marinero y con un ritmo tranquilo que engancha. Muchos se compran y se venden entre conocidos, y por eso cuesta encontrarlos. Si buscas uno, aquí te explico lo que miro y cómo te puedo ayudar.',
  'h2list': 'Llaüts en venta',
  'empty': 'Ahora mismo no tengo ningún llaüt en cartera. <a href="{P}/alertas/">Crea una alerta</a> y te aviso en cuanto entre uno, antes de que salga en ningún portal.',
  'wa': 'Hola Juan, busco un llaüt de segunda mano.',
  'body': '''<h2 id="s0">Qué es un llaüt</h2><p>Es una embarcación tradicional de las costas catalana, valenciana y balear, con proa y popa altas, quilla larga y, hoy, motor diésel intraborda de pocas revoluciones. Antes era de vela latina y de pesca; ahora la mayoría se usa para pasear, fondear en calas y pescar con calma. En catalán también se dice <em>llagut</em>, y en castellano, laúd.</p><ul><li><strong>De madera:</strong> los tradicionales, muchos hechos por carpinteros de ribera. Bonitos y muy marineros, pero piden mantenimiento cada año.</li><li><strong>De fibra:</strong> barcos modernos con la línea del llaüt y mucho menos mantenimiento.</li></ul>
<h2 id="s1">Qué mirar en un llaüt de madera</h2><ul><li><strong>Calafateo y tablazón:</strong> juntas entre tablas, zonas que lloran agua y tablas blandas.</li><li><strong>Quilla, roda y codaste:</strong> la madera se pudre antes donde se acumula agua dulce.</li><li><strong>Achique:</strong> cuánta agua entra con el barco amarrado. Algo es normal en madera; mucha, no.</li><li><strong>Motor y eje:</strong> horas, bocina y prensaestopas.</li><li><strong>Historial:</strong> cuándo se varó por última vez y qué se le hizo.</li></ul><p>En un llaüt de madera haría siempre un peritaje, y mejor con alguien que conozca la madera. Lo general lo tienes en <a href="{P}/guias/que-mirar-comprar-barco-segunda-mano.html">qué mirar al comprar un barco de segunda mano</a>.</p>
<h2 id="s2">Título y papeles</h2><p>El título va por la eslora de los papeles, como en cualquier barco: Licencia de Navegación hasta 6 metros, PNB hasta 8 y PER a partir de ahí. Muchos llaüts miden entre 6 y 9 metros. Comprueba la ITB, que no tenga cargas y que la documentación esté al día. Lo tienes en <a href="{P}/titulaciones/">titulaciones</a> y en <a href="{P}/guias/papeles-vender-barco-cambio-titularidad.html">papeles y cambio de titularidad</a>.</p>
<h2 id="s3">Cuánto cuesta</h2><p>Varía muchísimo. Un llaüt de madera que necesita trabajo puede salir barato y costar mucho después; uno restaurado y con facturas vale bastante más. Por eso, más que el precio de anuncio, miro el estado y lo que habrá que invertir el primer año. Si quieres una referencia general, tienes <a href="{P}/comprar/cuanto-cuesta-un-barco.html">cuánto cuesta un barco</a>.</p>
<h2 id="s4">¿Vendes tu llaüt?</h2><p>Hay pocos en el mercado y bastante gente buscándolos. Si tienes uno y piensas venderlo, <a href="{P}/vender-barco/">cuéntame qué tienes</a>.</p>''',
  'faq': [
   ('¿Qué diferencia hay entre llaüt, llagut y laúd?', 'Ninguna: llaüt y llagut son dos formas de decirlo en catalán, y laúd es como se dice en castellano.'),
   ('¿Es caro mantener un llaüt de madera?', 'Más que uno de fibra: la varada de cada año con repaso de calafateo y pintura es casi obligada. Si buscas pocas preocupaciones, un llaüt de fibra es más tranquilo.'),
   ('¿Dónde se encuentran llaüts de segunda mano?', 'Sobre todo en Baleares y en la costa de Cataluña y Valencia, y muchos se venden entre conocidos o en el mismo puerto. Si creas una alerta, te aviso cuando entre uno en mi cartera.'),
  ],
  'rel': [('{P}/alertas/', 'Avísame de barcos nuevos'), ('{P}/comprar/barcos-segunda-mano-baleares.html', 'Barcos de segunda mano en Baleares'), ('{P}/comprar/barcos-segunda-mano-cataluna.html', 'Barcos de segunda mano en Cataluña'), ('{P}/guias/itb-inspeccion-tecnica-barcos-recreo.html', 'La ITB de los barcos')],
 },
 'ca': {
  'title': 'Llaüts de segona mà en venda: què mirar i preus',
  'desc': 'Llaüts d\'ocasió a Catalunya i les Balears: fusta o fibra, què revisar (calafatament, quilla, motor), titulació necessària i com trobar-ne un. T\'aviso quan n\'entri un.',
  'eyebrow': 'Comprar vaixell · Llaüts',
  'h1': 'Llaüts de segona mà',
  'lead': 'El llaüt és el vaixell de tota la vida de la Mediterrània: noble, mariner i amb un ritme tranquil que enganxa. Molts es compren i es venen entre coneguts, i per això costa trobar-los. Si en busques un, aquí t\'explico què miro i com et puc ajudar.',
  'h2list': 'Llaüts en venda',
  'empty': 'Ara mateix no tinc cap llaüt en cartera. <a href="{P}/alertas/">Crea una alerta</a> i t\'aviso tan bon punt n\'entri un, abans que surti a cap portal.',
  'wa': 'Hola Juan, busco un llaüt de segona mà.',
  'body': '''<h2 id="s0">Què és un llaüt</h2><p>És una embarcació tradicional de les costes catalana, valenciana i balear, amb proa i popa altes, quilla llarga i, avui, motor dièsel intrabord de poques revolucions. Abans era de vela llatina i de pesca; ara la majoria es fa servir per passejar, fondejar a cales i pescar amb calma. També se'n diu <em>llagut</em>.</p><ul><li><strong>De fusta:</strong> els tradicionals, molts fets per mestres d'aixa. Bonics i molt mariners, però demanen manteniment cada any.</li><li><strong>De fibra:</strong> vaixells moderns amb la línia del llaüt i molt menys manteniment.</li></ul>
<h2 id="s1">Què mirar en un llaüt de fusta</h2><ul><li><strong>Calafatament i folre:</strong> juntes entre taules, zones que ploren aigua i taules toves.</li><li><strong>Quilla, roda i codast:</strong> la fusta es podreix abans on s'acumula aigua dolça.</li><li><strong>Buidatge:</strong> quanta aigua hi entra amb el vaixell amarrat. Una mica és normal en fusta; molta, no.</li><li><strong>Motor i eix:</strong> hores, botzina i premsaestopes.</li><li><strong>Historial:</strong> quan es va varar per últim cop i què s'hi va fer.</li></ul><p>En un llaüt de fusta faria sempre un peritatge, i millor amb algú que conegui la fusta. El que és general ho tens a <a href="{P}/guias/que-mirar-comprar-barco-segunda-mano.html">què mirar en comprar un vaixell de segona mà</a>.</p>
<h2 id="s2">Titulació i papers</h2><p>La titulació va per l'eslora dels papers, com en qualsevol vaixell: Llicència de Navegació fins a 6 metres, PNB fins a 8 i PER (a Catalunya, PEE) a partir d'aquí. Molts llaüts fan entre 6 i 9 metres. Comprova la ITB, que no tingui càrregues i que la documentació estigui al dia. Ho tens a <a href="{P}/titulaciones/">titulacions</a> i a <a href="{P}/guias/papeles-vender-barco-cambio-titularidad.html">papers i canvi de titularitat</a>.</p>
<h2 id="s3">Quant costa</h2><p>Varia moltíssim. Un llaüt de fusta que necessita feina pot sortir barat i costar molt després; un de restaurat i amb factures val força més. Per això, més que el preu d'anunci, miro l'estat i el que caldrà invertir el primer any. Si vols una referència general, tens <a href="{P}/comprar/cuanto-cuesta-un-barco.html">quant costa un vaixell</a>.</p>
<h2 id="s4">Vens el teu llaüt?</h2><p>N'hi ha pocs al mercat i força gent que en busca. Si en tens un i el penses vendre, <a href="{P}/vender-barco/">explica'm què tens</a>.</p>''',
  'faq': [
   ('Quina diferència hi ha entre llaüt i llagut?', 'Cap: són dues maneres de dir-ho en català. En castellà se\'n diu laúd.'),
   ('És car mantenir un llaüt de fusta?', 'Més que un de fibra: la varada de cada any amb repàs de calafatament i pintura és gairebé obligada. Si busques poques preocupacions, un llaüt de fibra és més tranquil.'),
   ('On es troben llaüts de segona mà?', 'Sobretot a les Balears i a la costa de Catalunya i València, i molts es venen entre coneguts o al mateix port. Si crees una alerta, t\'aviso quan n\'entri un a la meva cartera.'),
  ],
  'rel': [('{P}/alertas/', 'Avisa\'m de vaixells nous'), ('{P}/comprar/barcos-segunda-mano-baleares.html', 'Vaixells de segona mà a les Balears'), ('{P}/comprar/barcos-segunda-mano-cataluna.html', 'Vaixells de segona mà a Catalunya'), ('{P}/guias/itb-inspeccion-tecnica-barcos-recreo.html', 'La ITB dels vaixells')],
 },
 'en': {
  'title': 'Used llaüts for sale: what to check and prices',
  'desc': 'Pre-owned llaüts (traditional Mediterranean boats) in Catalonia and the Balearics: wood or GRP, what to check, licence needed and how to find one.',
  'eyebrow': 'Buy a boat · Llaüts',
  'h1': 'Used llaüts (traditional Mediterranean boats)',
  'lead': 'The llaüt is the classic boat of the western Mediterranean: handsome, seaworthy and with a relaxed pace that gets you hooked. Many are bought and sold between acquaintances, which is why they are hard to find. If you are looking for one, here is what I check and how I can help.',
  'h2list': 'Llaüts for sale',
  'empty': 'Right now I have no llaüt in my listings. <a href="{P}/alertas/">Create an alert</a> and I will let you know as soon as one comes in, before it goes on any portal.',
  'wa': 'Hi Juan, I am looking for a used llaüt.',
  'body': '''<h2 id="s0">What a llaüt is</h2><p>It is a traditional boat from the Catalan, Valencian and Balearic coasts, with a high bow and stern, a long keel and, today, a slow-revving inboard diesel. It used to be a lateen-rigged fishing boat; now most are used for cruising, anchoring in coves and relaxed fishing. In Spanish it is called <em>laúd</em>.</p><ul><li><strong>Wooden:</strong> the traditional ones, many built by local shipwrights. Beautiful and very seaworthy, but they need maintenance every year.</li><li><strong>GRP:</strong> modern boats with the llaüt's lines and far less maintenance.</li></ul>
<h2 id="s1">What to check on a wooden llaüt</h2><ul><li><strong>Caulking and planking:</strong> seams between planks, weeping areas and soft planks.</li><li><strong>Keel, stem and sternpost:</strong> wood rots first where fresh water collects.</li><li><strong>Bilge:</strong> how much water comes in while moored. Some is normal on wood; a lot is not.</li><li><strong>Engine and shaft:</strong> hours, stern tube and stuffing box.</li><li><strong>History:</strong> when it was last hauled out and what was done.</li></ul><p>On a wooden llaüt I would always get a survey, ideally by someone who knows wood. The general checklist is in <a href="{P}/guias/que-mirar-comprar-barco-segunda-mano.html">what to check when buying a used boat</a>.</p>
<h2 id="s2">Licence and papers</h2><p>The licence depends on the length on the papers, as with any boat: Licencia de Navegación up to 6 metres, PNB up to 8 and PER above that. Many llaüts are between 6 and 9 metres. Check the ITB, that there are no charges and that the paperwork is up to date. See <a href="{P}/titulaciones/">boating licences</a> and <a href="{P}/guias/papeles-vender-barco-cambio-titularidad.html">papers and change of ownership</a>.</p>
<h2 id="s3">How much it costs</h2><p>It varies enormously. A wooden llaüt that needs work can be cheap to buy and expensive afterwards; a restored one with invoices is worth much more. So rather than the asking price, I look at the condition and what will need investing in the first year. For a general reference, see <a href="{P}/comprar/cuanto-cuesta-un-barco.html">how much a boat costs</a>.</p>
<h2 id="s4">Selling your llaüt?</h2><p>There are few on the market and quite a few people looking. If you have one and are thinking of selling, <a href="{P}/vender-barco/">tell me about it</a>.</p>''',
  'faq': [
   ('What is the difference between llaüt, llagut and laúd?', 'None: llaüt and llagut are two Catalan spellings, and laúd is the Spanish word.'),
   ('Is a wooden llaüt expensive to maintain?', 'More than a GRP one: a yearly haul-out with caulking and paint is almost a must. If you want fewer worries, a GRP llaüt is easier.'),
   ('Where can I find a used llaüt?', 'Mainly in the Balearics and along the Catalan and Valencian coast, and many are sold between acquaintances or in the port itself. If you create an alert, I will let you know when one comes in.'),
  ],
  'rel': [('{P}/alertas/', 'Alert me of new boats'), ('{P}/comprar/barcos-segunda-mano-baleares.html', 'Used boats in the Balearics'), ('{P}/comprar/barcos-segunda-mano-cataluna.html', 'Used boats in Catalonia'), ('{P}/guias/itb-inspeccion-tecnica-barcos-recreo.html', 'The ITB boat inspection')],
 },
 'fr': {
  'title': 'Llaüts d’occasion à vendre : quoi vérifier et prix',
  'desc': 'Llaüts d’occasion (bateaux traditionnels méditerranéens) en Catalogne et aux Baléares : bois ou polyester, quoi vérifier, permis et comment en trouver un.',
  'eyebrow': 'Acheter un bateau · Llaüts',
  'h1': 'Llaüts d’occasion (bateaux traditionnels de Méditerranée)',
  'lead': 'Le llaüt est le bateau traditionnel de la Méditerranée occidentale, cousin du pointu : noble, marin et avec un rythme tranquille qui séduit. Beaucoup se vendent entre connaissances, c’est pourquoi ils sont difficiles à trouver. Si vous en cherchez un, voici ce que je vérifie et comment je peux vous aider.',
  'h2list': 'Llaüts à vendre',
  'empty': 'Pour l’instant, je n’ai aucun llaüt à vendre. <a href="{P}/alertas/">Créez une alerte</a> et je vous préviendrai dès qu’il en arrive un, avant qu’il ne soit publié sur un portail.',
  'wa': 'Bonjour Juan, je cherche un llaüt d’occasion.',
  'body': '''<h2 id="s0">Qu’est-ce qu’un llaüt</h2><p>C’est un bateau traditionnel des côtes catalane, valencienne et baléare, avec une étrave et une poupe hautes, une longue quille et, aujourd’hui, un moteur diesel in-bord à bas régime. Autrefois gréé en voile latine pour la pêche, il sert maintenant surtout à se promener, mouiller dans les criques et pêcher tranquillement. En espagnol, on dit <em>laúd</em>.</p><ul><li><strong>En bois :</strong> les traditionnels, souvent construits par des charpentiers de marine. Beaux et très marins, mais ils demandent de l’entretien chaque année.</li><li><strong>En polyester :</strong> des bateaux modernes aux lignes de llaüt, avec beaucoup moins d’entretien.</li></ul>
<h2 id="s1">Ce qu’il faut vérifier sur un llaüt en bois</h2><ul><li><strong>Calfatage et bordé :</strong> joints entre les bordages, zones qui suintent et bordages mous.</li><li><strong>Quille, étrave et étambot :</strong> le bois pourrit d’abord là où l’eau douce s’accumule.</li><li><strong>Fond de cale :</strong> combien d’eau entre au port. Un peu est normal sur du bois ; beaucoup, non.</li><li><strong>Moteur et ligne d’arbre :</strong> heures, tube d’étambot et presse-étoupe.</li><li><strong>Historique :</strong> date du dernier carénage et travaux effectués.</li></ul><p>Sur un llaüt en bois, je ferais toujours faire une expertise, idéalement par quelqu’un qui connaît le bois. La liste générale est dans <a href="{P}/guias/que-mirar-comprar-barco-segunda-mano.html">ce qu’il faut vérifier en achetant un bateau d’occasion</a>.</p>
<h2 id="s2">Permis et papiers</h2><p>En Espagne, le permis dépend de la longueur inscrite sur les papiers : Licencia de Navegación jusqu’à 6 mètres, PNB jusqu’à 8 et PER au-delà. Beaucoup de llaüts mesurent entre 6 et 9 mètres. Vérifiez l’ITB, l’absence de charges et que les papiers sont à jour. Si vous comptez l’immatriculer en France, lisez <a href="{P}/guias/comprar-barco-espana-matricular-francia.html">acheter un bateau en Espagne et l’immatriculer en France</a>.</p>
<h2 id="s3">Combien ça coûte</h2><p>Cela varie énormément. Un llaüt en bois qui demande des travaux peut être bon marché à l’achat et coûteux ensuite ; un llaüt restauré avec factures vaut bien plus. Plutôt que le prix affiché, je regarde l’état et ce qu’il faudra investir la première année. Pour une référence générale, voir <a href="{P}/comprar/cuanto-cuesta-un-barco.html">combien coûte un bateau</a>.</p>
<h2 id="s4">Vous vendez votre llaüt ?</h2><p>Il y en a peu sur le marché et pas mal d’acheteurs. Si vous en avez un et pensez le vendre, <a href="{P}/vender-barco/">parlez-m’en</a>.</p>''',
  'faq': [
   ('Quelle différence entre llaüt, llagut et laúd ?', 'Aucune : llaüt et llagut sont deux façons de l’écrire en catalan, et laúd est le mot espagnol.'),
   ('Un llaüt en bois coûte-t-il cher à entretenir ?', 'Plus qu’un llaüt en polyester : un carénage annuel avec reprise du calfatage et peinture est presque obligatoire. Pour être tranquille, un llaüt en polyester est plus simple.'),
   ('Où trouver un llaüt d’occasion ?', 'Surtout aux Baléares et sur les côtes de Catalogne et de Valence, et beaucoup se vendent entre connaissances ou au port. Si vous créez une alerte, je vous préviens quand un llaüt arrive.'),
  ],
  'rel': [('{P}/alertas/', 'Alertes nouveaux bateaux'), ('{P}/comprar/barcos-segunda-mano-baleares.html', 'Bateaux d’occasion aux Baléares'), ('{P}/comprar/barcos-segunda-mano-cataluna.html', 'Bateaux d’occasion en Catalogne'), ('{P}/guias/comprar-barco-espana-matricular-francia.html', 'Acheter en Espagne, immatriculer en France')],
 },
}

# ---------------------------------------------------------------- ¿Cuánto cuesta un barco?
_TBL = {
 'es': ('Tipo', 'Eslora', 'Rango habitual de segunda mano', [('Lancha open de consola central', '6 a 7 m', '20.000 a 60.000 €'), ('Sundeck', '7 a 8 m', '25.000 a 92.500 €'), ('Walkaround', '7 a 8,5 m', '32.000 a 120.000 €'), ('Pilothouse', '7,5 a 9 m', '45.000 a 180.000 €'), ('Cabinado o cruiser', '8 a 8,5 m', '35.000 a 67.000 €')]),
 'ca': ('Tipus', 'Eslora', 'Rang habitual de segona mà', [('Llanxa open de consola central', '6 a 7 m', '20.000 a 60.000 €'), ('Sundeck', '7 a 8 m', '25.000 a 92.500 €'), ('Walkaround', '7 a 8,5 m', '32.000 a 120.000 €'), ('Pilothouse', '7,5 a 9 m', '45.000 a 180.000 €'), ('Cabinat o cruiser', '8 a 8,5 m', '35.000 a 67.000 €')]),
 'en': ('Type', 'Length', 'Usual second-hand range', [('Centre-console open boat', '6 to 7 m', '€20,000 to €60,000'), ('Sundeck', '7 to 8 m', '€25,000 to €92,500'), ('Walkaround', '7 to 8.5 m', '€32,000 to €120,000'), ('Pilothouse', '7.5 to 9 m', '€45,000 to €180,000'), ('Cabin cruiser', '8 to 8.5 m', '€35,000 to €67,000')]),
 'fr': ('Type', 'Longueur', 'Fourchette d’occasion habituelle', [('Open à console centrale', '6 à 7 m', '20 000 à 60 000 €'), ('Sundeck', '7 à 8 m', '25 000 à 92 500 €'), ('Walkaround', '7 à 8,5 m', '32 000 à 120 000 €'), ('Pilothouse', '7,5 à 9 m', '45 000 à 180 000 €'), ('Cabin cruiser', '8 à 8,5 m', '35 000 à 67 000 €')]),
}
def _table(l):
    a, b, c, rows = _TBL[l]
    return '<table><thead><tr><th>%s</th><th>%s</th><th>%s</th></tr></thead><tbody>%s</tbody></table>' % (a, b, c, ''.join('<tr><td>%s</td><td>%s</td><td>%s</td></tr>' % r for r in rows))

PAGES['cuanto-cuesta-un-barco'] = {
 'filter': {},
 'list_after_intro': True,
 'fiscal': True,
 'es': {
  'title': '¿Cuánto cuesta un barco? Precios de segunda mano en 2026',
  'desc': 'Cuánto cuesta un barco de segunda mano según tipo y eslora (lancha, semirrígida, cabinado, velero, yate), qué impuestos pagas al comprarlo y cuánto cuesta tenerlo.',
  'eyebrow': 'Comprar barco · Precios',
  'h1': '¿Cuánto cuesta un barco? Precios de segunda mano por tipo y eslora',
  'lead': 'Es la primera pregunta de casi todo el mundo. La respuesta corta: desde unos pocos miles de euros por una neumática hasta cientos de miles por un yate. La útil tiene tres partes: lo que cuesta comprarlo, lo que pagas al comprarlo y lo que cuesta tenerlo.',
  'intro': '<h2 id="precio">Precio según tipo y eslora</h2><p>Estos son los rangos de anuncios reales de los modelos de 6 a 9 metros que sigo cada mes en la página de <a href="{P}/precios/">precios de barcos de ocasión</a>, con motor incluido:</p>' + _table('es') + '<p>Son precios que se piden; el de cierre suele quedar por debajo. Dentro de cada rango, lo que más mueve el precio es el año, el motor y sus horas, y si hay facturas.</p><h3>Semirrígidas, veleros y barcos grandes</h3><p>Para darte referencias reales, esto es lo que tengo ahora en cartera (octubre de 2026): dos semirrígidas de 5,35 y 6,50 metros entre 25.000 y 33.000 €; un velero de acero de 12 metros de 1981 por 72.000 € y un Beneteau Oceanis 50 de 2008 por 155.000 €; y un flybridge Jeanneau Prestige 32 de 2006, de 10,65 metros, por 89.000 €. Un barco grande y con años puede costar menos que una lancha pequeña recién salida de fábrica.</p>',
  'h2list': 'Barcos en venta ahora, con su precio',
  'wa': 'Hola Juan, quiero saber cuánto me costaría un barco.',
  'body': '''<h2 id="impuestos">Lo que pagas al comprarlo</h2><ul><li><strong>Si compras a un particular:</strong> el ITP, que en Cataluña es del 5 % sobre el precio o sobre el valor de las tablas de Hacienda si es mayor. Cada comunidad tiene su tipo: los tienes en la <a href="{P}/guias/itp-comprar-barco-usado-por-comunidad.html">guía del ITP por comunidad</a>.</li><li><strong>Si compras a una empresa:</strong> la operación lleva IVA en lugar de ITP.</li><li><strong>Si el barco viene de fuera y mide más de 8 metros:</strong> además, el <a href="{P}/guias/impuesto-matriculacion-barcos.html">impuesto de matriculación</a> del 12 %.</li><li><strong>Gestiones:</strong> cambio de titularidad en Capitanía y, si lo encargas, gestoría y peritaje.</li></ul><p>Haz la cuenta con la <a href="{P}/herramientas/impuestos-comprar-barco.html">calculadora de impuestos</a>.</p>
<h2 id="tenerlo">Lo que cuesta tenerlo cada año</h2><ul><li><strong>Amarre o marina seca:</strong> suele ser el gasto más grande. Tarifas de 19 puertos en la <a href="{P}/guias/amarres-cataluna-tipos-precios-alquiler-compra.html">guía de amarres</a>.</li><li><strong>Seguro:</strong> la responsabilidad civil es obligatoria.</li><li><strong>Mantenimiento:</strong> varada, antifouling, revisión del motor y pequeñas reparaciones.</li><li><strong>ITB:</strong> según eslora y lista.</li><li><strong>Combustible:</strong> depende de cuánto navegues y del motor.</li></ul><p>Calcula tu caso con la <a href="{P}/herramientas/coste-mantener-barco.html">calculadora de coste anual</a> o lee <a href="{P}/guias/cuanto-cuesta-mantener-un-barco-cataluna.html">cuánto cuesta mantener un barco en Cataluña</a>.</p>
<h2 id="bueno">Cómo saber si un precio es bueno</h2><p>Compáralo con anuncios del mismo modelo y año, pide facturas y pregunta cuánto tiempo lleva anunciado. Tienes rangos por año en las fichas de modelo, como el <a href="{P}/modelos/jeanneau-merry-fisher-795.html">Merry Fisher 795</a>, el <a href="{P}/modelos/jeanneau-cap-camarat-7-5-wa.html">Cap Camarat 7.5 WA</a> o el <a href="{P}/modelos/jeanneau-cap-camarat-8-5-wa.html">Cap Camarat 8.5 WA</a>, y el método completo en <a href="{P}/guias/precio-barco-ocasion.html">cómo poner precio a un barco de ocasión</a>.</p>''',
  'faq': [
   ('¿Cuánto cuesta un barco pequeño?', 'Una neumática o una lancha pequeña de segunda mano se puede encontrar por unos pocos miles de euros. Una lancha open de 6 a 7 metros en buen estado se mueve entre unos 20.000 y 60.000 €.'),
   ('¿Cuánto cuesta un yate?', 'Depende de lo que llames yate. Un barco con cabina y flybridge de 10 a 12 metros y unos años puede rondar los 100.000 €, y los yates de 15 metros o más se cuentan en cientos de miles o en millones.'),
   ('¿Cuánto cuesta mantener un barco al año?', 'Depende sobre todo del amarre, de la eslora y de cuánto navegues. Con la calculadora de coste anual puedes hacer la cuenta de tu caso.'),
  ],
  'rel': [('{P}/precios/', 'Precios por modelo'), ('{P}/herramientas/', 'Calculadoras'), ('{P}/guias/itp-comprar-barco-usado-por-comunidad.html', 'ITP por comunidad autónoma'), ('{P}/comprar/', 'Comprar un barco de segunda mano')],
 },
 'ca': {
  'title': 'Quant costa un vaixell? Preus de segona mà el 2026',
  'desc': 'Quant costa un vaixell de segona mà segons tipus i eslora (llanxa, semirígida, cabinat, veler, iot), quins impostos pagues en comprar-lo i quant costa tenir-lo.',
  'eyebrow': 'Comprar vaixell · Preus',
  'h1': 'Quant costa un vaixell? Preus de segona mà per tipus i eslora',
  'lead': 'És la primera pregunta de gairebé tothom. La resposta curta: des d\'uns pocs milers d\'euros per una neumàtica fins a centenars de milers per un iot. La útil té tres parts: el que costa comprar-lo, el que pagues en comprar-lo i el que costa tenir-lo.',
  'intro': '<h2 id="precio">Preu segons tipus i eslora</h2><p>Aquests són els rangs d\'anuncis reals dels models de 6 a 9 metres que segueixo cada mes a la pàgina de <a href="{P}/precios/">preus de vaixells d\'ocasió</a>, amb motor inclòs:</p>' + _table('ca') + '<p>Són preus demanats; el de tancament sol quedar per sota. Dins de cada rang, el que més mou el preu és l\'any, el motor i les hores, i si hi ha factures.</p><h3>Semirígides, velers i vaixells grans</h3><p>Per donar-te referències reals, això és el que tinc ara en cartera (octubre de 2026): dues semirígides de 5,35 i 6,50 metres entre 25.000 i 33.000 €; un veler d\'acer de 12 metres de 1981 per 72.000 € i un Beneteau Oceanis 50 de 2008 per 155.000 €; i un flybridge Jeanneau Prestige 32 de 2006, de 10,65 metres, per 89.000 €. Un vaixell gran i amb anys pot costar menys que una llanxa petita acabada de sortir de fàbrica.</p>',
  'h2list': 'Vaixells en venda ara, amb el seu preu',
  'wa': 'Hola Juan, vull saber quant em costaria un vaixell.',
  'body': '''<h2 id="impuestos">El que pagues en comprar-lo</h2><ul><li><strong>Si compres a un particular:</strong> l'ITP, que a Catalunya és del 5 % sobre el preu o sobre el valor de les taules d'Hisenda si és més alt. Cada comunitat té el seu tipus: els tens a la <a href="{P}/guias/itp-comprar-barco-usado-por-comunidad.html">guia de l'ITP per comunitat</a>.</li><li><strong>Si compres a una empresa:</strong> l'operació porta IVA en lloc d'ITP.</li><li><strong>Si el vaixell ve de fora i fa més de 8 metres:</strong> a més, l'<a href="{P}/guias/impuesto-matriculacion-barcos.html">impost de matriculació</a> del 12 %.</li><li><strong>Gestions:</strong> canvi de titularitat a Capitania i, si ho encarregues, gestoria i peritatge.</li></ul><p>Fes el càlcul amb la <a href="{P}/herramientas/impuestos-comprar-barco.html">calculadora d'impostos</a>.</p>
<h2 id="tenerlo">El que costa tenir-lo cada any</h2><ul><li><strong>Amarrador o marina seca:</strong> sol ser la despesa més gran. Tarifes de 19 ports a la <a href="{P}/guias/amarres-cataluna-tipos-precios-alquiler-compra.html">guia d'amarradors</a>.</li><li><strong>Assegurança:</strong> la responsabilitat civil és obligatòria.</li><li><strong>Manteniment:</strong> varada, antiincrustant, revisió del motor i petites reparacions.</li><li><strong>ITB:</strong> segons eslora i llista.</li><li><strong>Combustible:</strong> depèn de quant naveguis i del motor.</li></ul><p>Calcula el teu cas amb la <a href="{P}/herramientas/coste-mantener-barco.html">calculadora de cost anual</a> o llegeix <a href="{P}/guias/cuanto-cuesta-mantener-un-barco-cataluna.html">quant costa mantenir un vaixell a Catalunya</a>.</p>
<h2 id="bueno">Com saber si un preu és bo</h2><p>Compara'l amb anuncis del mateix model i any, demana factures i pregunta quant de temps fa que està anunciat. Tens rangs per any a les fitxes de model, com el <a href="{P}/modelos/jeanneau-merry-fisher-795.html">Merry Fisher 795</a>, el <a href="{P}/modelos/jeanneau-cap-camarat-7-5-wa.html">Cap Camarat 7.5 WA</a> o el <a href="{P}/modelos/jeanneau-cap-camarat-8-5-wa.html">Cap Camarat 8.5 WA</a>, i el mètode complet a <a href="{P}/guias/precio-barco-ocasion.html">com posar preu a un vaixell d'ocasió</a>.</p>''',
  'faq': [
   ('Quant costa un vaixell petit?', 'Una neumàtica o una llanxa petita de segona mà es pot trobar per uns pocs milers d\'euros. Una llanxa open de 6 a 7 metres en bon estat es mou entre uns 20.000 i 60.000 €.'),
   ('Quant costa un iot?', 'Depèn del que en diguis iot. Un vaixell amb cabina i flybridge de 10 a 12 metres i uns anys pot rondar els 100.000 €, i els iots de 15 metres o més es compten en centenars de milers o en milions.'),
   ('Quant costa mantenir un vaixell l\'any?', 'Depèn sobretot de l\'amarrador, de l\'eslora i de quant naveguis. Amb la calculadora de cost anual pots fer el càlcul del teu cas.'),
  ],
  'rel': [('{P}/precios/', 'Preus per model'), ('{P}/herramientas/', 'Calculadores'), ('{P}/guias/itp-comprar-barco-usado-por-comunidad.html', 'ITP per comunitat autònoma'), ('{P}/comprar/', 'Comprar un vaixell de segona mà')],
 },
 'en': {
  'title': 'How much does a boat cost? Used boat prices in Spain 2026',
  'desc': 'How much a used boat costs in Spain by type and length (open boat, RIB, cabin cruiser, sailboat, yacht), what taxes you pay when buying and the yearly running costs.',
  'eyebrow': 'Buy a boat · Prices',
  'h1': 'How much does a boat cost? Used boat prices by type and length',
  'lead': 'It is almost everyone\'s first question. The short answer: from a few thousand euros for an inflatable to hundreds of thousands for a yacht. The useful answer has three parts: what it costs to buy, what you pay when buying and what it costs to keep.',
  'intro': '<h2 id="precio">Price by type and length</h2><p>These are the ranges of real listings for the 6 to 9-metre models I track every month on the <a href="{P}/precios/">used boat prices</a> page, engine included:</p>' + _table('en') + '<p>These are asking prices; the sale price is usually lower. Within each range, what moves the price most is the year, the engine and its hours, and whether there are invoices.</p><h3>RIBs, sailboats and larger boats</h3><p>To give you real references, this is what I have listed now (October 2026): two RIBs of 5.35 and 6.50 metres between €25,000 and €33,000; a 12-metre 1981 steel sailboat for €72,000 and a 2008 Beneteau Oceanis 50 for €155,000; and a 2006 Jeanneau Prestige 32 flybridge, 10.65 metres, for €89,000. A large older boat can cost less than a small brand-new one.</p>',
  'h2list': 'Boats for sale now, with their price',
  'wa': 'Hi Juan, I would like to know how much a boat would cost me.',
  'body': '''<h2 id="impuestos">What you pay when buying (Spain)</h2><ul><li><strong>Buying from a private seller:</strong> transfer tax (ITP), 5% in Catalonia on the price or on the tax authority's table value if higher. Each region has its own rate: see the <a href="{P}/guias/itp-comprar-barco-usado-por-comunidad.html">ITP guide by region</a>.</li><li><strong>Buying from a company:</strong> VAT applies instead of ITP.</li><li><strong>If the boat comes from abroad and is over 8 metres:</strong> also the 12% <a href="{P}/guias/impuesto-matriculacion-barcos.html">registration tax</a>.</li><li><strong>Paperwork:</strong> change of ownership at the Harbour Master's office and, if you use them, an agency and a survey.</li></ul><p>Work it out with the <a href="{P}/herramientas/impuestos-comprar-barco.html">tax calculator</a>.</p>
<h2 id="tenerlo">What it costs to keep each year</h2><ul><li><strong>Berth or dry stack:</strong> usually the biggest cost. Rates for 19 ports in the <a href="{P}/guias/amarres-cataluna-tipos-precios-alquiler-compra.html">berth guide</a>.</li><li><strong>Insurance:</strong> third-party liability is compulsory.</li><li><strong>Maintenance:</strong> haul-out, antifouling, engine service and small repairs.</li><li><strong>ITB:</strong> depending on length and list.</li><li><strong>Fuel:</strong> depends on how much you go out and the engine.</li></ul><p>Work out your case with the <a href="{P}/herramientas/coste-mantener-barco.html">yearly cost calculator</a> or read <a href="{P}/guias/cuanto-cuesta-mantener-un-barco-cataluna.html">how much it costs to keep a boat in Catalonia</a>.</p>
<h2 id="bueno">How to tell if a price is good</h2><p>Compare it with listings of the same model and year, ask for invoices and ask how long it has been for sale. There are ranges by year on the model pages, such as the <a href="{P}/modelos/jeanneau-merry-fisher-795.html">Merry Fisher 795</a>, the <a href="{P}/modelos/jeanneau-cap-camarat-7-5-wa.html">Cap Camarat 7.5 WA</a> or the <a href="{P}/modelos/jeanneau-cap-camarat-8-5-wa.html">Cap Camarat 8.5 WA</a>, and the full method in <a href="{P}/guias/precio-barco-ocasion.html">how to price a used boat</a>.</p>''',
  'faq': [
   ('How much does a small boat cost?', 'A used inflatable or small boat can be found for a few thousand euros. A 6 to 7-metre open boat in good condition is between about €20,000 and €60,000.'),
   ('How much does a yacht cost?', 'It depends on what you call a yacht. A 10 to 12-metre flybridge cruiser a few years old can be around €100,000, and yachts of 15 metres or more run into hundreds of thousands or millions.'),
   ('How much does it cost to keep a boat each year?', 'It depends mainly on the berth, the length and how much you use it. The yearly cost calculator lets you work out your own case.'),
  ],
  'rel': [('{P}/precios/', 'Prices by model'), ('{P}/herramientas/', 'Calculators'), ('{P}/guias/itp-comprar-barco-usado-por-comunidad.html', 'ITP by region'), ('{P}/comprar/', 'Buying a used boat')],
 },
 'fr': {
  'title': 'Combien coûte un bateau ? Prix d’occasion en Espagne en 2026',
  'desc': 'Combien coûte un bateau d’occasion en Espagne selon le type et la longueur (open, semi-rigide, cabin cruiser, voilier, yacht), les taxes à l’achat et le coût annuel.',
  'eyebrow': 'Acheter un bateau · Prix',
  'h1': 'Combien coûte un bateau ? Prix d’occasion par type et longueur',
  'lead': 'C’est la première question de presque tout le monde. La réponse courte : de quelques milliers d’euros pour un pneumatique à des centaines de milliers pour un yacht. La réponse utile a trois parties : le prix d’achat, ce que vous payez à l’achat et ce que coûte le bateau à l’année.',
  'intro': '<h2 id="precio">Prix selon le type et la longueur</h2><p>Voici les fourchettes d’annonces réelles des modèles de 6 à 9 mètres que je suis chaque mois sur la page <a href="{P}/precios/">prix des bateaux d’occasion</a>, moteur compris :</p>' + _table('fr') + '<p>Ce sont des prix demandés ; le prix de vente est généralement plus bas. Dans chaque fourchette, ce qui fait le plus varier le prix, c’est l’année, le moteur et ses heures, et l’existence de factures.</p><h3>Semi-rigides, voiliers et grands bateaux</h3><p>Pour vous donner des références réelles, voici ce que j’ai actuellement (octobre 2026) : deux semi-rigides de 5,35 et 6,50 mètres entre 25 000 et 33 000 € ; un voilier en acier de 12 mètres de 1981 à 72 000 € et un Beneteau Oceanis 50 de 2008 à 155 000 € ; et un flybridge Jeanneau Prestige 32 de 2006, de 10,65 mètres, à 89 000 €. Un grand bateau ancien peut coûter moins qu’un petit bateau neuf.</p>',
  'h2list': 'Bateaux à vendre maintenant, avec leur prix',
  'wa': 'Bonjour Juan, j’aimerais savoir combien me coûterait un bateau.',
  'body': '''<h2 id="impuestos">Ce que vous payez à l’achat (en Espagne)</h2><ul><li><strong>Achat à un particulier :</strong> l’ITP (droits de mutation), 5 % en Catalogne sur le prix ou sur la valeur fiscale si elle est supérieure. Chaque région a son taux : voir le <a href="{P}/guias/itp-comprar-barco-usado-por-comunidad.html">guide de l’ITP par région</a>.</li><li><strong>Achat à une entreprise :</strong> TVA au lieu de l’ITP.</li><li><strong>Bateau venant de l’étranger de plus de 8 mètres :</strong> en plus, la <a href="{P}/guias/impuesto-matriculacion-barcos.html">taxe d’immatriculation</a> de 12 %.</li><li><strong>Démarches :</strong> changement de propriétaire à la Capitainerie et, si besoin, agence et expertise.</li></ul><p>Si vous comptez immatriculer le bateau en France, lisez <a href="{P}/guias/comprar-barco-espana-matricular-francia.html">acheter un bateau en Espagne et l’immatriculer en France</a>.</p>
<h2 id="tenerlo">Ce que coûte le bateau chaque année</h2><ul><li><strong>Place de port ou port à sec :</strong> souvent la plus grosse dépense. Tarifs de 19 ports dans le <a href="{P}/guias/amarres-cataluna-tipos-precios-alquiler-compra.html">guide des places de port</a>.</li><li><strong>Assurance :</strong> la responsabilité civile est obligatoire.</li><li><strong>Entretien :</strong> carénage, antifouling, révision du moteur et petites réparations.</li><li><strong>ITB :</strong> selon la longueur et la liste.</li><li><strong>Carburant :</strong> selon votre usage et le moteur.</li></ul><p>Faites votre calcul avec le <a href="{P}/herramientas/coste-mantener-barco.html">calculateur de coût annuel</a> ou lisez <a href="{P}/guias/cuanto-cuesta-mantener-un-barco-cataluna.html">combien coûte l’entretien d’un bateau en Catalogne</a>.</p>
<h2 id="bueno">Comment savoir si un prix est bon</h2><p>Comparez avec des annonces du même modèle et de la même année, demandez les factures et depuis combien de temps il est en vente. Vous trouverez des fourchettes par année sur les fiches modèles, comme le <a href="{P}/modelos/jeanneau-merry-fisher-795.html">Merry Fisher 795</a>, le <a href="{P}/modelos/jeanneau-cap-camarat-7-5-wa.html">Cap Camarat 7.5 WA</a> ou le <a href="{P}/modelos/jeanneau-cap-camarat-8-5-wa.html">Cap Camarat 8.5 WA</a>, et la méthode complète dans <a href="{P}/guias/precio-barco-ocasion.html">comment fixer le prix d’un bateau d’occasion</a>.</p>''',
  'faq': [
   ('Combien coûte un petit bateau ?', 'Un pneumatique ou un petit bateau d’occasion se trouve pour quelques milliers d’euros. Un open de 6 à 7 mètres en bon état se situe entre environ 20 000 et 60 000 €.'),
   ('Combien coûte un yacht ?', 'Cela dépend de ce qu’on appelle un yacht. Un flybridge de 10 à 12 mètres de quelques années peut tourner autour de 100 000 €, et les yachts de 15 mètres et plus se comptent en centaines de milliers ou en millions.'),
   ('Combien coûte un bateau à l’année ?', 'Cela dépend surtout de la place de port, de la longueur et de votre usage. Le calculateur de coût annuel vous permet de faire votre propre calcul.'),
  ],
  'rel': [('{P}/precios/', 'Prix par modèle'), ('{P}/herramientas/', 'Calculateurs'), ('{P}/guias/itp-comprar-barco-usado-por-comunidad.html', 'ITP par région'), ('{P}/comprar/', 'Acheter un bateau d’occasion')],
 },
}
