# -*- coding: utf-8 -*-
# Contenido de las landings SEO de octubre de 2026 (ES/CA/EN/FR).
# {P} = prefijo de idioma en los enlaces internos ('' en ES, '/ca', '/en', '/fr').

PAGES = {}

# ---------------------------------------------------------------- 6 metros con camarote
PAGES['barcos-6-metros-con-camarote-segunda-mano'] = {
 'filter': {"maxLen": 7.5, "types": ["cabinado", "pilothouse", "walkaround"]},
 'es': {
  'title': 'Barcos de 6 metros con camarote de segunda mano en venta',
  'desc': 'Barcos de 6 a 7,5 metros con camarote, de ocasión: tipos, qué título necesitas, precios orientativos y modelos que miraría. Con barcos en venta.',
  'eyebrow': 'Comprar barco · 6 a 7,5 metros',
  'h1': 'Barcos de 6 metros con camarote de segunda mano',
  'lead': 'Es de lo que más me piden: un barco manejable, que quepa en un amarre asequible y que tenga dónde guardar cosas, echarse una siesta o pasar alguna noche. Aquí tienes los que tengo en venta de esa eslora y lo que yo miraría antes de comprar uno.',
  'h2list': 'Barcos con camarote de 6 a 7,5 metros en venta',
  'wa': 'Hola Juan, busco un barco de unos 6 metros con camarote.',
  'body': '''<h2 id="s0">Qué es «camarote» en un barco de 6 metros</h2><p>En esta eslora casi nunca hay un camarote como tal, sino una cabina en la proa con una cama en V para dos adultos, a veces con WC. Según cómo esté pensado el barco, encontrarás:</p><ul><li><strong>Cabinado:</strong> la cabina ocupa la proa y la bañera queda a popa. Es lo más habitual en 6 metros.</li><li><strong>Pilothouse:</strong> el puesto de gobierno va cerrado. Ideal para pescar y para navegar todo el año.</li><li><strong>Walkaround:</strong> pasillos laterales para ir a proa y una cabina pequeña debajo. Muy cómodo para fondear.</li><li><strong>Sundeck con cabina:</strong> solárium en proa y una cabina pequeña debajo; más para calas que para dormir.</li></ul><p>Si vas a dormir a bordo, métete dentro en la visita: mide la cama, mira la altura y piensa en la ventilación. En 6 metros las diferencias entre modelos son grandes.</p>
<h2 id="s1">Qué título necesitas</h2><p>Lo que cuenta es la eslora que figura en los papeles, no la del anuncio.</p><ul><li><strong>Hasta 6 metros:</strong> Licencia de Navegación, de día y sin alejarte más de 2 millas de un puerto o abrigo.</li><li><strong>Hasta 8 metros:</strong> PNB, hasta 5 millas.</li><li><strong>Para ir más lejos:</strong> PER.</li></ul><p>Muchos barcos que se anuncian «de 6 metros» miden 6,2 o 6,5 m en los papeles, y entonces ya no basta con la Licencia. Pide la hoja de asiento o el certificado de registro antes de ir a verlo. Lo tienes explicado en <a href="{P}/titulaciones/">titulaciones</a>.</p>
<h2 id="s2">Cuánto cuesta</h2><p>Depende mucho del año, del motor y de la marca. Como referencia, en los modelos de 6 a 7 metros que sigo cada mes los anuncios van de unos 20.000 a 60.000 €, y un pilothouse de 7,5 metros como el <a href="{P}/modelos/jeanneau-merry-fisher-795.html">Merry Fisher 795 de segunda mano</a> va de 45.000 a 105.000 € según el año. Son precios que se piden, no de cierre. Tienes los rangos por modelo en <a href="{P}/precios/">precios de barcos de ocasión</a>.</p>
<h2 id="s3">Modelos que miraría</h2><p>Con cabina y en esta eslora se ven mucho el Jeanneau Merry Fisher 605 y 695, el Beneteau Antares de 6 y 7 metros y, en barcos más antiguos, marcas españolas como Faeton o Rio. Si buscas más solárium que cabina, mira el <a href="{P}/modelos/quicksilver-activ-675-sundeck.html">Quicksilver Activ 675 Sundeck</a> o el <a href="{P}/modelos/beneteau-flyer-7-7-sundeck.html">Beneteau Flyer 7.7 SUNdeck</a>. Y si puedes subir a 7 metros largos, el <a href="{P}/modelos/jeanneau-cap-camarat-7-5-wa.html">Cap Camarat 7.5 WA</a> es de los walkaround más buscados.</p>
<h2 id="s4">Qué mirar antes de comprar</h2><ul><li><strong>Humedad en la cabina:</strong> juntas de portillos y escotilla, manchas y olor a cerrado.</li><li><strong>Motor:</strong> horas y facturas; en un fueraborda, si ha tenido su revisión cada año.</li><li><strong>Remolque:</strong> muchos de esta eslora se guardan en seco; si lo lleva, comprueba que tenga sus papeles en regla.</li><li><strong>Papeles:</strong> eslora, ITB y que no tenga cargas.</li></ul><p>Más detalle en <a href="{P}/guias/que-mirar-comprar-barco-segunda-mano.html">qué mirar al comprar un barco de segunda mano</a>.</p>''',
  'faq': [
   ('¿Puedo llevar un barco de 6 metros con la Licencia de Navegación?', 'Sí, si la eslora de los papeles no pasa de 6 metros y el motor es el adecuado para el barco según el fabricante. Solo de día y sin alejarte más de 2 millas de un puerto o abrigo.'),
   ('¿Se puede dormir en un barco de 6 metros?', 'Para un fin de semana, dos adultos sí, en la cama en V de proa. Para más días se agradece un barco de 7 metros o más con WC y algo de cocina.'),
   ('¿Cuánto cuesta el amarre de un barco de 6 metros?', 'Varía mucho según el puerto y la temporada. Tienes las tarifas de 19 puertos catalanes en la guía de amarres, y muchos barcos de esta eslora se guardan en seco, que puede salir más barato.'),
  ],
  'rel': [('{P}/titulaciones/', 'Titulaciones náuticas'), ('{P}/precios/', 'Precios de barcos de ocasión'), ('{P}/guias/amarres-cataluna-tipos-precios-alquiler-compra.html', 'Amarres en Cataluña: precios'), ('{P}/comprar/lanchas-motor-segunda-mano.html', 'Lanchas a motor de segunda mano')],
 },
 'ca': {
  'title': 'Vaixells de 6 metres amb cabina de segona mà en venda',
  'desc': 'Vaixells de 6 a 7,5 metres amb cabina, d\'ocasió: tipus, quina titulació necessites, preus orientatius i models que miraria. Amb vaixells en venda.',
  'eyebrow': 'Comprar vaixell · 6 a 7,5 metres',
  'h1': 'Vaixells de 6 metres amb cabina de segona mà',
  'lead': 'És del que més em demanen: un vaixell manejable, que càpiga en un amarrador assequible i que tingui on guardar coses, fer una becaina o passar alguna nit. Aquí tens els que tinc en venda d\'aquesta eslora i el que jo miraria abans de comprar-ne un.',
  'h2list': 'Vaixells amb cabina de 6 a 7,5 metres en venda',
  'wa': 'Hola Juan, busco un vaixell d\'uns 6 metres amb cabina.',
  'body': '''<h2 id="s0">Què vol dir «cabina» en un vaixell de 6 metres</h2><p>En aquesta eslora gairebé mai hi ha una cabina com a tal, sinó un espai a proa amb un llit en V per a dos adults, de vegades amb WC. Segons com estigui pensat el vaixell, trobaràs:</p><ul><li><strong>Cabinat:</strong> la cabina ocupa la proa i la banyera queda a popa. És el més habitual en 6 metres.</li><li><strong>Pilothouse:</strong> el lloc de govern és tancat. Ideal per pescar i navegar tot l'any.</li><li><strong>Walkaround:</strong> passadissos laterals per anar a proa i una cabina petita a sota. Molt còmode per fondejar.</li><li><strong>Sundeck amb cabina:</strong> solàrium a proa i una cabina petita a sota; més per a cales que per dormir.</li></ul><p>Si hi has de dormir, fica-t'hi a dins durant la visita: mesura el llit, mira l'alçada i pensa en la ventilació. En 6 metres les diferències entre models són grans.</p>
<h2 id="s1">Quina titulació necessites</h2><p>El que compta és l'eslora que consta als papers, no la de l'anunci.</p><ul><li><strong>Fins a 6 metres:</strong> Llicència de Navegació, de dia i sense allunyar-te més de 2 milles d'un port o abric.</li><li><strong>Fins a 8 metres:</strong> PNB, fins a 5 milles.</li><li><strong>Per anar més lluny:</strong> PER (a Catalunya, PEE).</li></ul><p>Molts vaixells que s'anuncien «de 6 metres» fan 6,2 o 6,5 m als papers, i aleshores ja no n'hi ha prou amb la Llicència. Demana el full d'assentament o el certificat de registre abans d'anar-lo a veure. Ho tens explicat a <a href="{P}/titulaciones/">titulacions</a>.</p>
<h2 id="s2">Quant costa</h2><p>Depèn molt de l'any, del motor i de la marca. Com a referència, en els models de 6 a 7 metres que segueixo cada mes els anuncis van d'uns 20.000 a 60.000 €, i un pilothouse de 7,5 metres com el <a href="{P}/modelos/jeanneau-merry-fisher-795.html">Merry Fisher 795 de segona mà</a> va de 45.000 a 105.000 € segons l'any. Són preus demanats, no de tancament. Tens els rangs per model a <a href="{P}/precios/">preus de vaixells d'ocasió</a>.</p>
<h2 id="s3">Models que miraria</h2><p>Amb cabina i en aquesta eslora es veuen molt el Jeanneau Merry Fisher 605 i 695, el Beneteau Antares de 6 i 7 metres i, en vaixells més antics, marques espanyoles com Faeton o Rio. Si busques més solàrium que cabina, mira el <a href="{P}/modelos/quicksilver-activ-675-sundeck.html">Quicksilver Activ 675 Sundeck</a> o el <a href="{P}/modelos/beneteau-flyer-7-7-sundeck.html">Beneteau Flyer 7.7 SUNdeck</a>. I si pots pujar a 7 metres llargs, el <a href="{P}/modelos/jeanneau-cap-camarat-7-5-wa.html">Cap Camarat 7.5 WA</a> és dels walkaround més buscats.</p>
<h2 id="s4">Què mirar abans de comprar</h2><ul><li><strong>Humitat a la cabina:</strong> juntes de portells i escotilla, taques i olor de tancat.</li><li><strong>Motor:</strong> hores i factures; en un forabord, si ha tingut la revisió cada any.</li><li><strong>Remolc:</strong> molts d'aquesta eslora es guarden en sec; si en porta, comprova que tingui els papers en regla.</li><li><strong>Papers:</strong> eslora, ITB i que no tingui càrregues.</li></ul><p>Més detall a <a href="{P}/guias/que-mirar-comprar-barco-segunda-mano.html">què mirar en comprar un vaixell de segona mà</a>.</p>''',
  'faq': [
   ('Puc portar un vaixell de 6 metres amb la Llicència de Navegació?', 'Sí, si l\'eslora dels papers no passa de 6 metres i el motor és l\'adequat per al vaixell segons el fabricant. Només de dia i sense allunyar-te més de 2 milles d\'un port o abric.'),
   ('Es pot dormir en un vaixell de 6 metres?', 'Per a un cap de setmana, dos adults sí, al llit en V de proa. Per a més dies s\'agraeix un vaixell de 7 metres o més amb WC i una mica de cuina.'),
   ('Quant costa l\'amarrador d\'un vaixell de 6 metres?', 'Varia molt segons el port i la temporada. Tens les tarifes de 19 ports catalans a la guia d\'amarradors, i molts vaixells d\'aquesta eslora es guarden en sec, que pot sortir més barat.'),
  ],
  'rel': [('{P}/titulaciones/', 'Titulacions nàutiques'), ('{P}/precios/', 'Preus de vaixells d\'ocasió'), ('{P}/guias/amarres-cataluna-tipos-precios-alquiler-compra.html', 'Amarradors a Catalunya: preus'), ('{P}/comprar/lanchas-motor-segunda-mano.html', 'Llanxes a motor de segona mà')],
 },
 'en': {
  'title': 'Used 6-metre boats with a cabin for sale',
  'desc': 'Pre-owned boats of 6 to 7.5 metres with a cabin: types, which licence you need, guide prices and models worth a look. With boats for sale.',
  'eyebrow': 'Buy a boat · 6 to 7.5 metres',
  'h1': 'Used 6-metre boats with a cabin',
  'lead': 'It is one of the most common requests I get: an easy-to-handle boat that fits an affordable berth and has somewhere to store gear, take a nap or spend the odd night. Here are the ones I have for sale in that size and what I would check before buying one.',
  'h2list': 'Boats with a cabin from 6 to 7.5 metres for sale',
  'wa': 'Hi Juan, I am looking for a boat of around 6 metres with a cabin.',
  'body': '''<h2 id="s0">What "cabin" means on a 6-metre boat</h2><p>At this length there is rarely a proper cabin, but rather a space in the bow with a V-berth for two adults, sometimes with a toilet. Depending on the layout, you will find:</p><ul><li><strong>Cabin cruiser:</strong> the cabin takes the bow and the cockpit is aft. The most common layout at 6 metres.</li><li><strong>Pilothouse:</strong> an enclosed helm. Ideal for fishing and year-round boating.</li><li><strong>Walkaround:</strong> side decks to walk forward and a small cabin below. Very handy at anchor.</li><li><strong>Sundeck with cabin:</strong> a bow sunpad with a small cabin below; more for coves than for sleeping.</li></ul><p>If you plan to sleep aboard, get inside during the viewing: measure the berth, check the headroom and think about ventilation. At 6 metres the differences between models are big.</p>
<h2 id="s1">Which licence you need</h2><p>What counts is the length on the registration papers, not the one in the ad.</p><ul><li><strong>Up to 6 metres:</strong> Licencia de Navegación, daylight only and within 2 miles of a port or shelter.</li><li><strong>Up to 8 metres:</strong> PNB, up to 5 miles.</li><li><strong>To go further:</strong> PER.</li></ul><p>Many boats advertised as "6 metres" measure 6.2 or 6.5 m on paper, and then the Licencia is no longer enough. Ask for the registry extract before going to see it. More in <a href="{P}/titulaciones/">boating licences</a>.</p>
<h2 id="s2">How much it costs</h2><p>It depends a lot on the year, the engine and the brand. As a guide, for the 6 to 7-metre models I track every month, asking prices run from about €20,000 to €60,000, and a 7.5-metre pilothouse such as the <a href="{P}/modelos/jeanneau-merry-fisher-795.html">used Merry Fisher 795</a> goes from €45,000 to €105,000 depending on the year. These are asking prices, not sale prices. See the ranges by model in <a href="{P}/precios/">used boat prices</a>.</p>
<h2 id="s3">Models I would look at</h2><p>With a cabin and at this length you often see the Jeanneau Merry Fisher 605 and 695, the Beneteau Antares 6 and 7 metres and, on older boats, Spanish brands such as Faeton or Rio. If you want more sunpad than cabin, look at the <a href="{P}/modelos/quicksilver-activ-675-sundeck.html">Quicksilver Activ 675 Sundeck</a> or the <a href="{P}/modelos/beneteau-flyer-7-7-sundeck.html">Beneteau Flyer 7.7 SUNdeck</a>. And if you can stretch to just over 7 metres, the <a href="{P}/modelos/jeanneau-cap-camarat-7-5-wa.html">Cap Camarat 7.5 WA</a> is one of the most sought-after walkarounds.</p>
<h2 id="s4">What to check before buying</h2><ul><li><strong>Damp in the cabin:</strong> window and hatch seals, stains and a musty smell.</li><li><strong>Engine:</strong> hours and invoices; on an outboard, whether it has been serviced every year.</li><li><strong>Trailer:</strong> many boats of this size are kept ashore; if it has one, check its paperwork is in order.</li><li><strong>Papers:</strong> length, ITB (technical inspection) and no outstanding charges.</li></ul><p>More in <a href="{P}/guias/que-mirar-comprar-barco-segunda-mano.html">what to check when buying a used boat</a>.</p>''',
  'faq': [
   ('Can I skipper a 6-metre boat with the Licencia de Navegación?', 'Yes, if the length on the papers is no more than 6 metres and the engine is suitable for the boat according to the builder. Daylight only and within 2 miles of a port or shelter.'),
   ('Can you sleep on a 6-metre boat?', 'For a weekend, two adults can, in the bow V-berth. For longer trips a boat of 7 metres or more with a toilet and a small galley is much nicer.'),
   ('How much does a berth for a 6-metre boat cost?', 'It varies a lot by port and season. The berth guide has the rates of 19 Catalan ports, and many boats of this size are kept ashore, which can work out cheaper.'),
  ],
  'rel': [('{P}/titulaciones/', 'Boating licences'), ('{P}/precios/', 'Used boat prices'), ('{P}/guias/amarres-cataluna-tipos-precios-alquiler-compra.html', 'Berths in Catalonia: prices'), ('{P}/comprar/lanchas-motor-segunda-mano.html', 'Used motorboats')],
 },
 'fr': {
  'title': 'Bateaux de 6 mètres avec cabine d’occasion à vendre',
  'desc': 'Bateaux d’occasion de 6 à 7,5 mètres avec cabine : types, permis nécessaire, prix indicatifs et modèles à regarder. Avec des bateaux à vendre.',
  'eyebrow': 'Acheter un bateau · 6 à 7,5 mètres',
  'h1': 'Bateaux de 6 mètres avec cabine d’occasion',
  'lead': 'C’est l’une des demandes les plus fréquentes : un bateau facile à manœuvrer, qui tient dans une place de port abordable et qui offre un endroit pour ranger, faire la sieste ou passer une nuit. Voici ceux que j’ai à vendre dans cette taille et ce que je vérifierais avant d’en acheter un.',
  'h2list': 'Bateaux avec cabine de 6 à 7,5 mètres à vendre',
  'wa': 'Bonjour Juan, je cherche un bateau d’environ 6 mètres avec cabine.',
  'body': '''<h2 id="s0">Ce que veut dire « cabine » sur un bateau de 6 mètres</h2><p>À cette taille, il y a rarement une vraie cabine, plutôt un espace à l’avant avec une couchette en V pour deux adultes, parfois avec WC. Selon la conception du bateau, vous trouverez :</p><ul><li><strong>Cabin cruiser :</strong> la cabine occupe l’avant et le cockpit est à l’arrière. Le plus courant à 6 mètres.</li><li><strong>Pilothouse (timonerie) :</strong> poste de pilotage fermé. Idéal pour la pêche et la navigation toute l’année.</li><li><strong>Walkaround :</strong> passavants pour aller à l’avant et petite cabine dessous. Très pratique au mouillage.</li><li><strong>Sundeck avec cabine :</strong> bain de soleil à l’avant et petite cabine dessous ; plus pour les criques que pour dormir.</li></ul><p>Si vous comptez dormir à bord, entrez dans la cabine lors de la visite : mesurez la couchette, regardez la hauteur et pensez à l’aération. À 6 mètres, les différences entre modèles sont grandes.</p>
<h2 id="s1">Quel permis faut-il</h2><p>C’est la longueur inscrite sur les papiers qui compte, pas celle de l’annonce. Les permis espagnols :</p><ul><li><strong>Jusqu’à 6 mètres :</strong> Licencia de Navegación, de jour et à 2 milles maximum d’un port ou d’un abri.</li><li><strong>Jusqu’à 8 mètres :</strong> PNB, jusqu’à 5 milles.</li><li><strong>Pour aller plus loin :</strong> PER.</li></ul><p>Beaucoup de bateaux annoncés « 6 mètres » mesurent 6,2 ou 6,5 m sur les papiers. Demandez l’extrait d’immatriculation avant la visite. Si vous avez un permis français, consultez la page <a href="{P}/titulaciones/">permis bateau</a>.</p>
<h2 id="s2">Combien ça coûte</h2><p>Cela dépend beaucoup de l’année, du moteur et de la marque. À titre indicatif, pour les modèles de 6 à 7 mètres que je suis chaque mois, les annonces vont d’environ 20 000 à 60 000 €, et une pilothouse de 7,5 mètres comme le <a href="{P}/modelos/jeanneau-merry-fisher-795.html">Merry Fisher 795 d’occasion</a> va de 45 000 à 105 000 € selon l’année. Ce sont des prix demandés, pas des prix de vente. Voir les fourchettes par modèle dans <a href="{P}/precios/">prix des bateaux d’occasion</a>.</p>
<h2 id="s3">Modèles que je regarderais</h2><p>Avec cabine et à cette taille, on voit beaucoup le Jeanneau Merry Fisher 605 et 695, le Beneteau Antares de 6 et 7 mètres et, sur les bateaux plus anciens, des marques espagnoles comme Faeton ou Rio. Si vous voulez plus de bain de soleil que de cabine, regardez le <a href="{P}/modelos/quicksilver-activ-675-sundeck.html">Quicksilver Activ 675 Sundeck</a> ou le <a href="{P}/modelos/beneteau-flyer-7-7-sundeck.html">Beneteau Flyer 7.7 SUNdeck</a>. Et si vous pouvez passer à un peu plus de 7 mètres, le <a href="{P}/modelos/jeanneau-cap-camarat-7-5-wa.html">Cap Camarat 7.5 WA</a> est l’un des walkarounds les plus recherchés.</p>
<h2 id="s4">Ce qu’il faut vérifier avant d’acheter</h2><ul><li><strong>Humidité dans la cabine :</strong> joints des hublots et du panneau de pont, taches et odeur de renfermé.</li><li><strong>Moteur :</strong> heures et factures ; pour un hors-bord, s’il a été révisé chaque année.</li><li><strong>Remorque :</strong> beaucoup de bateaux de cette taille sont stockés à terre ; s’il y en a une, vérifiez que ses papiers sont en règle.</li><li><strong>Papiers :</strong> longueur, ITB (contrôle technique) et absence de charges.</li></ul><p>Plus de détails dans <a href="{P}/guias/que-mirar-comprar-barco-segunda-mano.html">ce qu’il faut vérifier en achetant un bateau d’occasion</a>.</p>''',
  'faq': [
   ('Peut-on piloter un bateau de 6 mètres avec la Licencia de Navegación ?', 'Oui, si la longueur inscrite sur les papiers ne dépasse pas 6 mètres et que le moteur est adapté au bateau selon le constructeur. De jour uniquement et à 2 milles maximum d’un port ou d’un abri.'),
   ('Peut-on dormir sur un bateau de 6 mètres ?', 'Pour un week-end, deux adultes oui, dans la couchette en V avant. Pour plus de jours, un bateau de 7 mètres ou plus avec WC et un coin cuisine est bien plus agréable.'),
   ('Combien coûte une place de port pour un bateau de 6 mètres ?', 'Cela varie beaucoup selon le port et la saison. Le guide des places de port donne les tarifs de 19 ports catalans, et beaucoup de bateaux de cette taille sont stockés à terre, ce qui peut revenir moins cher.'),
  ],
  'rel': [('{P}/titulaciones/', 'Permis bateau'), ('{P}/precios/', 'Prix des bateaux d’occasion'), ('{P}/guias/amarres-cataluna-tipos-precios-alquiler-compra.html', 'Places de port en Catalogne : prix'), ('{P}/comprar/lanchas-motor-segunda-mano.html', 'Bateaux à moteur d’occasion')],
 },
}

# ---------------------------------------------------------------- Semirrígidas
PAGES['semirrigidas-neumaticas-segunda-mano'] = {
 'filter': {"types": ["rib"]},
 'es': {
  'title': 'Semirrígidas y neumáticas de segunda mano en venta',
  'desc': 'Semirrígidas (RIB) y neumáticas de ocasión en venta: qué mirar en los flotadores, PVC o Hypalon, motor, título necesario y precios. Con barcos en venta.',
  'eyebrow': 'Comprar barco · Semirrígidas',
  'h1': 'Semirrígidas y neumáticas de segunda mano en venta',
  'lead': 'Las semirrígidas son de los barcos que mejor se mueven de segunda mano: ligeras, estables, con poco calado y fáciles de guardar en seco. Estas son las que tengo ahora y lo que miro siempre antes de recomendar una.',
  'h2list': 'Semirrígidas en venta',
  'wa': 'Hola Juan, busco una semirrígida de segunda mano.',
  'body': '''<h2 id="s0">Semirrígida o neumática: en qué se diferencian</h2><p>La <strong>neumática</strong> es toda hinchable, con suelo de lamas, hinchable o de madera: ligera, se pliega y cabe en un maletero, pero con mar navega peor. La <strong>semirrígida</strong> (RIB) tiene un casco rígido de fibra o aluminio con flotadores alrededor: navega mucho mejor, admite más motor y es la que se usa para ir a calas o como auxiliar de un barco grande.</p><p>Mucha gente las llama «zodiac» por la marca, pero hay muchos fabricantes: Zodiac, Bombard, Capelli, Joker Boat, BSC, Lomac, Sacs o Tiger Marine, entre otros.</p>
<h2 id="s1">Qué mirar en los flotadores</h2><ul><li><strong>Material:</strong> PVC o Hypalon (CSM). El Hypalon suele aguantar mejor el sol y durar más; el PVC es más barato. Pregunta cuál lleva y de qué año son los flotadores.</li><li><strong>Estanqueidad:</strong> pide que estén hinchados desde el día anterior. Si han perdido presión, hay fugas en válvulas o costuras.</li><li><strong>Pegados:</strong> zonas despegadas, parches y la unión del flotador con el casco.</li><li><strong>Aspecto:</strong> un flotador muy descolorido, pegajoso o con grietas está al final de su vida.</li></ul><p>Cambiar los flotadores de una semirrígida de 6 metros es un gasto importante, de varios miles de euros: tenlo en cuenta en el precio.</p>
<h2 id="s2">Casco, consola y motor</h2><ul><li><strong>Casco:</strong> golpes en la quilla por varadas o por el remolque, y el espejo de popa firme alrededor de los tornillos del motor.</li><li><strong>Motor fueraborda:</strong> horas, facturas y revisión anual (aceites, impulsor, ánodos).</li><li><strong>Remolque:</strong> luces, rodillos y papeles.</li></ul><p>Más detalle en <a href="{P}/guias/que-mirar-comprar-barco-segunda-mano.html">qué mirar al comprar un barco de segunda mano</a>.</p>
<h2 id="s3">Qué título necesitas</h2><p>Hasta 6 metros de eslora en los papeles, la <strong>Licencia de Navegación</strong>, siempre que el motor sea el adecuado para el barco según el fabricante. Una semirrígida de 6,5 metros ya pide el <strong>PNB</strong>. Por eso la semirrígida de 6 metros es de las más buscadas. Lo tienes en <a href="{P}/titulaciones/">titulaciones</a>.</p>
<h2 id="s4">Cuánto cuesta</h2><p>En una semirrígida pesan más los flotadores y el motor que el año del casco. Como referencia, las dos que tengo ahora en cartera, de 5,35 y 6,50 metros con motores de 115 y 150 CV, se anuncian entre 25.000 y 33.000 € (octubre de 2026). Una neumática pequeña de segunda mano cuesta bastante menos.</p>''',
  'faq': [
   ('¿Cuánto duran los flotadores de una semirrígida?', 'Depende del material, del sol y de cómo se haya guardado. Como orientación, el PVC dura menos que el Hypalon, y un barco guardado bajo techo o con funda los conserva mucho mejor. Si son los originales y el barco tiene muchos años, cuenta con cambiarlos.'),
   ('¿Qué título necesito para una semirrígida de 6 metros?', 'Con 6 metros o menos en los papeles, la Licencia de Navegación, siempre que el motor sea el adecuado según el fabricante. Si mide más, el PNB.'),
   ('¿Una semirrígida tiene que pasar la ITB?', 'Si está en lista 7ª y mide menos de 6 metros de casco, no tiene reconocimientos periódicos. Con 6 metros o más, como máximo cada 5 años. Lo explico en la guía de la ITB.'),
  ],
  'rel': [('{P}/guias/itb-inspeccion-tecnica-barcos-recreo.html', 'La ITB de los barcos'), ('{P}/titulaciones/', 'Titulaciones náuticas'), ('{P}/comprar/barcos-6-metros-con-camarote-segunda-mano.html', 'Barcos de 6 metros con camarote'), ('{P}/comprar/lanchas-motor-segunda-mano.html', 'Lanchas a motor de segunda mano')],
 },
 'ca': {
  'title': 'Semirígides i neumàtiques de segona mà en venda',
  'desc': 'Semirígides (RIB) i neumàtiques d\'ocasió en venda: què mirar als flotadors, PVC o Hypalon, motor, titulació necessària i preus. Amb vaixells en venda.',
  'eyebrow': 'Comprar vaixell · Semirígides',
  'h1': 'Semirígides i neumàtiques de segona mà en venda',
  'lead': 'Les semirígides són dels vaixells que millor es mouen de segona mà: lleugeres, estables, amb poc calat i fàcils de guardar en sec. Aquestes són les que tinc ara i el que miro sempre abans de recomanar-ne una.',
  'h2list': 'Semirígides en venda',
  'wa': 'Hola Juan, busco una semirígida de segona mà.',
  'body': '''<h2 id="s0">Semirígida o neumàtica: en què es diferencien</h2><p>La <strong>neumàtica</strong> és tota inflable, amb terra de llistons, inflable o de fusta: lleugera, es plega i cap en un maleter, però amb mar navega pitjor. La <strong>semirígida</strong> (RIB) té un buc rígid de fibra o alumini amb flotadors al voltant: navega molt millor, admet més motor i és la que es fa servir per anar a cales o com a auxiliar d'un vaixell gran.</p><p>Molta gent en diu «zodiac» per la marca, però hi ha molts fabricants: Zodiac, Bombard, Capelli, Joker Boat, BSC, Lomac, Sacs o Tiger Marine, entre d'altres.</p>
<h2 id="s1">Què mirar als flotadors</h2><ul><li><strong>Material:</strong> PVC o Hypalon (CSM). L'Hypalon sol aguantar millor el sol i durar més; el PVC és més barat. Pregunta quin porta i de quin any són els flotadors.</li><li><strong>Estanquitat:</strong> demana que estiguin inflats des del dia abans. Si han perdut pressió, hi ha fuites a les vàlvules o a les costures.</li><li><strong>Encolats:</strong> zones desenganxades, pedaços i la unió del flotador amb el buc.</li><li><strong>Aspecte:</strong> un flotador molt descolorit, enganxós o amb esquerdes és al final de la seva vida.</li></ul><p>Canviar els flotadors d'una semirígida de 6 metres és una despesa important, de diversos milers d'euros: tingues-ho en compte en el preu.</p>
<h2 id="s2">Buc, consola i motor</h2><ul><li><strong>Buc:</strong> cops a la quilla per varades o pel remolc, i el mirall de popa ferm al voltant dels cargols del motor.</li><li><strong>Motor forabord:</strong> hores, factures i revisió anual (olis, impulsor, ànodes).</li><li><strong>Remolc:</strong> llums, corrons i papers.</li></ul><p>Més detall a <a href="{P}/guias/que-mirar-comprar-barco-segunda-mano.html">què mirar en comprar un vaixell de segona mà</a>.</p>
<h2 id="s3">Quina titulació necessites</h2><p>Fins a 6 metres d'eslora als papers, la <strong>Llicència de Navegació</strong>, sempre que el motor sigui l'adequat per al vaixell segons el fabricant. Una semirígida de 6,5 metres ja demana el <strong>PNB</strong>. Per això la semirígida de 6 metres és de les més buscades. Ho tens a <a href="{P}/titulaciones/">titulacions</a>.</p>
<h2 id="s4">Quant costa</h2><p>En una semirígida pesen més els flotadors i el motor que l'any del buc. Com a referència, les dues que tinc ara en cartera, de 5,35 i 6,50 metres amb motors de 115 i 150 CV, s'anuncien entre 25.000 i 33.000 € (octubre de 2026). Una neumàtica petita de segona mà costa força menys.</p>''',
  'faq': [
   ('Quant duren els flotadors d\'una semirígida?', 'Depèn del material, del sol i de com s\'hagi guardat. Com a orientació, el PVC dura menys que l\'Hypalon, i un vaixell guardat sota sostre o amb funda els conserva molt millor. Si són els originals i el vaixell té molts anys, compta a canviar-los.'),
   ('Quina titulació necessito per a una semirígida de 6 metres?', 'Amb 6 metres o menys als papers, la Llicència de Navegació, sempre que el motor sigui l\'adequat segons el fabricant. Si fa més, el PNB.'),
   ('Una semirígida ha de passar la ITB?', 'Si és a la llista 7a i fa menys de 6 metres de buc, no té reconeixements periòdics. Amb 6 metres o més, com a màxim cada 5 anys. Ho explico a la guia de la ITB.'),
  ],
  'rel': [('{P}/guias/itb-inspeccion-tecnica-barcos-recreo.html', 'La ITB dels vaixells'), ('{P}/titulaciones/', 'Titulacions nàutiques'), ('{P}/comprar/barcos-6-metros-con-camarote-segunda-mano.html', 'Vaixells de 6 metres amb cabina'), ('{P}/comprar/lanchas-motor-segunda-mano.html', 'Llanxes a motor de segona mà')],
 },
 'en': {
  'title': 'Used RIBs and inflatable boats for sale',
  'desc': 'Pre-owned RIBs and inflatable boats for sale: what to check on the tubes, PVC or Hypalon, engine, licence needed and prices. With boats for sale.',
  'eyebrow': 'Buy a boat · RIBs',
  'h1': 'Used RIBs and inflatable boats for sale',
  'lead': 'RIBs are among the boats that sell best second-hand: light, stable, shallow draught and easy to keep ashore. These are the ones I have now and what I always check before recommending one.',
  'h2list': 'RIBs for sale',
  'wa': 'Hi Juan, I am looking for a used RIB.',
  'body': '''<h2 id="s0">RIB or inflatable: the difference</h2><p>An <strong>inflatable</strong> is fully inflatable, with a slatted, inflatable or wooden floor: light, folds up and fits in a car boot, but handles worse in a sea. A <strong>RIB</strong> (rigid inflatable boat) has a rigid GRP or aluminium hull with tubes around it: it handles much better, takes a bigger engine and is the one used for trips to coves or as a tender for a large boat.</p><p>In Spain many people call them "zodiac" after the brand, but there are many builders: Zodiac, Bombard, Capelli, Joker Boat, BSC, Lomac, Sacs and Tiger Marine, among others.</p>
<h2 id="s1">What to check on the tubes</h2><ul><li><strong>Material:</strong> PVC or Hypalon (CSM). Hypalon usually stands up better to the sun and lasts longer; PVC is cheaper. Ask which one it has and how old the tubes are.</li><li><strong>Airtightness:</strong> ask for them to be inflated the day before. If they have lost pressure, valves or seams are leaking.</li><li><strong>Bonding:</strong> areas coming unstuck, patches and the joint between tube and hull.</li><li><strong>Appearance:</strong> a very faded, sticky or cracked tube is at the end of its life.</li></ul><p>Replacing the tubes on a 6-metre RIB is a major cost, several thousand euros: factor it into the price.</p>
<h2 id="s2">Hull, console and engine</h2><ul><li><strong>Hull:</strong> keel damage from groundings or the trailer, and a solid transom around the engine bolts.</li><li><strong>Outboard:</strong> hours, invoices and annual service (oils, impeller, anodes).</li><li><strong>Trailer:</strong> lights, rollers and paperwork.</li></ul><p>More in <a href="{P}/guias/que-mirar-comprar-barco-segunda-mano.html">what to check when buying a used boat</a>.</p>
<h2 id="s3">Which licence you need</h2><p>Up to 6 metres on the papers, the <strong>Licencia de Navegación</strong>, as long as the engine is suitable for the boat according to the builder. A 6.5-metre RIB already needs the <strong>PNB</strong>. That is why 6-metre RIBs are so sought after. More in <a href="{P}/titulaciones/">boating licences</a>.</p>
<h2 id="s4">How much it costs</h2><p>On a RIB the tubes and the engine matter more than the hull year. As a guide, the two I currently have, of 5.35 and 6.50 metres with 115 and 150 hp engines, are listed between €25,000 and €33,000 (October 2026). A small used inflatable costs much less.</p>''',
  'faq': [
   ('How long do RIB tubes last?', 'It depends on the material, the sun and how the boat has been stored. As a rough guide, PVC lasts less than Hypalon, and a boat kept under cover or with a cover keeps them much better. If they are the original tubes on an old boat, budget for replacing them.'),
   ('Which licence do I need for a 6-metre RIB?', 'With 6 metres or less on the papers, the Licencia de Navegación, as long as the engine is suitable according to the builder. If longer, the PNB.'),
   ('Does a RIB need the ITB inspection?', 'If it is on list 7 and its hull is under 6 metres, it has no periodic inspections. At 6 metres or more, at least every 5 years. I explain it in the ITB guide.'),
  ],
  'rel': [('{P}/guias/itb-inspeccion-tecnica-barcos-recreo.html', 'The ITB boat inspection'), ('{P}/titulaciones/', 'Boating licences'), ('{P}/comprar/barcos-6-metros-con-camarote-segunda-mano.html', '6-metre boats with a cabin'), ('{P}/comprar/lanchas-motor-segunda-mano.html', 'Used motorboats')],
 },
 'fr': {
  'title': 'Semi-rigides et pneumatiques d’occasion à vendre',
  'desc': 'Semi-rigides et pneumatiques d’occasion à vendre : quoi vérifier sur les flotteurs, PVC ou Hypalon, moteur, permis nécessaire et prix. Avec des bateaux à vendre.',
  'eyebrow': 'Acheter un bateau · Semi-rigides',
  'h1': 'Semi-rigides et pneumatiques d’occasion à vendre',
  'lead': 'Les semi-rigides font partie des bateaux qui se vendent le mieux d’occasion : légers, stables, peu de tirant d’eau et faciles à stocker à terre. Voici ceux que j’ai actuellement et ce que je vérifie toujours avant d’en recommander un.',
  'h2list': 'Semi-rigides à vendre',
  'wa': 'Bonjour Juan, je cherche un semi-rigide d’occasion.',
  'body': '''<h2 id="s0">Semi-rigide ou pneumatique : la différence</h2><p>Le <strong>pneumatique</strong> est entièrement gonflable, avec un plancher à lattes, gonflable ou en bois : léger, il se plie et tient dans un coffre, mais il navigue moins bien dans le clapot. Le <strong>semi-rigide</strong> a une coque rigide en polyester ou en aluminium entourée de flotteurs : il navigue bien mieux, accepte plus de puissance et c’est celui qu’on utilise pour aller aux criques ou comme annexe d’un grand bateau.</p><p>On les appelle souvent « zodiac » d’après la marque, mais il existe beaucoup de chantiers : Zodiac, Bombard, Capelli, Joker Boat, BSC, Lomac, Sacs ou Tiger Marine, entre autres.</p>
<h2 id="s1">Ce qu’il faut vérifier sur les flotteurs</h2><ul><li><strong>Matériau :</strong> PVC ou Hypalon (CSM). L’Hypalon résiste généralement mieux au soleil et dure plus longtemps ; le PVC est moins cher. Demandez lequel et de quelle année sont les flotteurs.</li><li><strong>Étanchéité :</strong> demandez qu’ils soient gonflés depuis la veille. S’ils ont perdu de la pression, il y a des fuites aux valves ou aux coutures.</li><li><strong>Collages :</strong> zones décollées, rustines et jonction entre flotteur et coque.</li><li><strong>Aspect :</strong> un flotteur très décoloré, collant ou craquelé est en fin de vie.</li></ul><p>Remplacer les flotteurs d’un semi-rigide de 6 mètres coûte cher, plusieurs milliers d’euros : tenez-en compte dans le prix.</p>
<h2 id="s2">Coque, console et moteur</h2><ul><li><strong>Coque :</strong> chocs sur la quille dus à des échouages ou à la remorque, et tableau arrière bien sain autour des fixations du moteur.</li><li><strong>Hors-bord :</strong> heures, factures et révision annuelle (huiles, turbine, anodes).</li><li><strong>Remorque :</strong> feux, rouleaux et papiers.</li></ul><p>Plus de détails dans <a href="{P}/guias/que-mirar-comprar-barco-segunda-mano.html">ce qu’il faut vérifier en achetant un bateau d’occasion</a>.</p>
<h2 id="s3">Quel permis faut-il</h2><p>En Espagne, jusqu’à 6 mètres sur les papiers, la <strong>Licencia de Navegación</strong>, à condition que le moteur soit adapté au bateau selon le constructeur. Un semi-rigide de 6,5 mètres demande déjà le <strong>PNB</strong>. Voir la page <a href="{P}/titulaciones/">permis bateau</a>.</p>
<h2 id="s4">Combien ça coûte</h2><p>Sur un semi-rigide, les flotteurs et le moteur comptent plus que l’année de la coque. À titre indicatif, les deux que j’ai actuellement, de 5,35 et 6,50 mètres avec des moteurs de 115 et 150 ch, sont annoncés entre 25 000 et 33 000 € (octobre 2026). Un petit pneumatique d’occasion coûte bien moins.</p>''',
  'faq': [
   ('Combien de temps durent les flotteurs d’un semi-rigide ?', 'Cela dépend du matériau, du soleil et du stockage. À titre indicatif, le PVC dure moins que l’Hypalon, et un bateau gardé à l’abri ou bâché les conserve bien mieux. Si ce sont les flotteurs d’origine sur un bateau ancien, prévoyez de les changer.'),
   ('Quel permis pour un semi-rigide de 6 mètres en Espagne ?', 'Avec 6 mètres ou moins sur les papiers, la Licencia de Navegación, à condition que le moteur soit adapté selon le constructeur. Au-delà, le PNB.'),
   ('Un semi-rigide doit-il passer l’ITB ?', 'S’il est en liste 7 et que sa coque mesure moins de 6 mètres, il n’a pas de visites périodiques. À partir de 6 mètres, au maximum tous les 5 ans. Je l’explique dans le guide de l’ITB.'),
  ],
  'rel': [('{P}/guias/itb-inspeccion-tecnica-barcos-recreo.html', 'L’ITB des bateaux'), ('{P}/titulaciones/', 'Permis bateau'), ('{P}/comprar/barcos-6-metros-con-camarote-segunda-mano.html', 'Bateaux de 6 mètres avec cabine'), ('{P}/comprar/lanchas-motor-segunda-mano.html', 'Bateaux à moteur d’occasion')],
 },
}
