# -*- coding: utf-8 -*-
# Motos de agua de segunda mano (ES/CA/EN/FR). {P} = prefijo de idioma.
# Fuente de titulaciones: RD 875/2014 (art. 3.4 definición, art. 8.d PNB, art. 10.2, art. 11.1 Licencia de Navegación).
PAGES = {}
PAGES['motos-de-agua-segunda-mano'] = {
 'filter': {"kind": "moto-agua"},
 'fiscal': True,
 'es': {
  'title': 'Motos de agua de segunda mano en venta: qué mirar y título',
  'desc': 'Motos de agua de ocasión: qué revisar antes de comprar (horas, turbina, casco, papeles), qué título necesitas y qué influye en el precio. Te aviso cuando entre una.',
  'eyebrow': 'Comprar · Motos de agua',
  'h1': 'Motos de agua de segunda mano',
  'lead': 'Una moto de agua de segunda mano puede ser una buena compra o un disgusto, y casi siempre se nota en lo que no se ve en las fotos: cómo se ha usado y cómo se ha cuidado. Aquí te cuento qué miro antes de recomendar una y qué papeles necesitas.',
  'h2list': 'Motos de agua en venta',
  'empty': 'Ahora mismo no tengo ninguna moto de agua en cartera. <a href="{P}/alertas/">Crea una alerta</a> y te aviso en cuanto entre una, antes de que salga en ningún portal.',
  'wa': 'Hola Juan, busco una moto de agua de segunda mano.',
  'body': '''<h2 id="s0">Qué mirar antes de comprar</h2><ul><li><strong>Horas de motor:</strong> el contador no lo es todo, pero cuenta. Pregunta también qué uso ha tenido: no es lo mismo un particular que unas vacaciones al año que una moto de alquiler.</li><li><strong>Mantenimiento:</strong> facturas de la revisión anual (aceite, bujías, ánodos, filtros) y si se ha lavado con agua dulce después de cada salida, sobre todo el circuito de refrigeración.</li><li><strong>Turbina e impulsor:</strong> golpes o desgaste por piedras y arena. Una turbina dañada se nota en la aceleración y en vibraciones.</li><li><strong>Casco:</strong> golpes, grietas o reparaciones en la parte de abajo, por varadas o por el remolque.</li><li><strong>Motor:</strong> que arranque en frío sin problemas y no se caliente en marcha. Si lleva compresor, pregunta cuándo se revisó.</li><li><strong>Remolque:</strong> luces, rodillos y que tenga sus papeles en regla.</li></ul><p>Si la moto lo merece, una revisión de un taller de motos de agua antes de pagar sale barata comparada con una avería. Lo general lo tienes en <a href="{P}/guias/que-mirar-comprar-barco-segunda-mano.html">qué mirar al comprar de segunda mano</a>.</p>
<h2 id="s1">Qué título necesitas</h2><p>Para gobernar una moto de agua hace falta titulación: la <strong>Licencia de Navegación</strong> o superior. Con la Licencia puedes llevarla de día y sin alejarte más de 2 millas de un puerto o lugar de abrigo. El PNB también la cubre, dentro de los límites de navegación de la propia moto. Lo tienes explicado en <a href="{P}/titulaciones/">titulaciones</a>.</p><p>En verano, respeta los canales balizados para salir y entrar de la playa y las zonas de baño: es donde más multas se ponen.</p>
<h2 id="s2">Papeles y lo que pagas al comprar</h2><ul><li>Comprueba que esté matriculada a nombre del vendedor y que no tenga cargas.</li><li>El seguro de responsabilidad civil es obligatorio.</li><li>Si compras a un particular, pagas el ITP de tu comunidad (en Cataluña, el 5 %). Lo tienes por comunidades en la <a href="{P}/guias/itp-comprar-barco-usado-por-comunidad.html">guía del ITP</a>.</li><li>Después, el cambio de titularidad. Te lo explico en <a href="{P}/guias/papeles-vender-barco-cambio-titularidad.html">papeles y cambio de titularidad</a>.</li></ul>
<h2 id="s3">Qué influye en el precio</h2><p>La marca y el modelo, la potencia, el año, las horas y, sobre todo, el estado y las facturas. Una moto de pocos años con muchas horas de alquiler puede valer menos que una más antigua de particular bien cuidada. Si me dices modelo, año y horas, te digo si un precio está en mercado.</p>
<h2 id="s4">¿Vendes tu moto de agua?</h2><p>Si tienes una y piensas venderla, <a href="{P}/vender-barco/">cuéntame qué tienes</a>. La trabajo igual que un barco: precio con criterio, anuncio cuidado y atención a los interesados.</p>''',
  'faq': [
   ('¿Se puede llevar una moto de agua sin título?', 'No. El Real Decreto 875/2014 exige titulación para gobernar motos náuticas: como mínimo, la Licencia de Navegación.'),
   ('¿Qué título necesito para una moto de agua?', 'La Licencia de Navegación o superior. Con la Licencia, de día y sin alejarte más de 2 millas de un puerto o abrigo. El PNB también habilita para motos náuticas, dentro de sus límites técnicos.'),
   ('¿Cuántas horas son muchas en una moto de agua?', 'Depende del modelo y, sobre todo, del mantenimiento. Más que la cifra, mira las facturas y qué uso ha tenido: una moto de alquiler suele acumular muchas horas en poco tiempo.'),
  ],
  'rel': [('{P}/titulaciones/', 'Titulaciones náuticas'), ('{P}/comprar/semirrigidas-neumaticas-segunda-mano.html', 'Semirrígidas de segunda mano'), ('{P}/comprar/cuanto-cuesta-un-barco.html', '¿Cuánto cuesta un barco?'), ('{P}/alertas/', 'Avísame cuando entre una')],
 },
 'ca': {
  'title': 'Motos d\'aigua de segona mà en venda: què mirar i titulació',
  'desc': 'Motos d\'aigua d\'ocasió: què revisar abans de comprar (hores, turbina, buc, papers), quina titulació necessites i què influeix en el preu. T\'aviso quan n\'entri una.',
  'eyebrow': 'Comprar · Motos d\'aigua',
  'h1': 'Motos d\'aigua de segona mà',
  'lead': 'Una moto d\'aigua de segona mà pot ser una bona compra o un disgust, i gairebé sempre es nota en el que no es veu a les fotos: com s\'ha fet servir i com s\'ha cuidat. Aquí t\'explico què miro abans de recomanar-ne una i quins papers necessites.',
  'h2list': 'Motos d\'aigua en venda',
  'empty': 'Ara mateix no tinc cap moto d\'aigua en cartera. <a href="{P}/alertas/">Crea una alerta</a> i t\'aviso tan bon punt n\'entri una, abans que surti a cap portal.',
  'wa': 'Hola Juan, busco una moto d\'aigua de segona mà.',
  'body': '''<h2 id="s0">Què mirar abans de comprar</h2><ul><li><strong>Hores de motor:</strong> el comptador no ho és tot, però compta. Pregunta també quin ús ha tingut: no és el mateix un particular que unes vacances l'any que una moto de lloguer.</li><li><strong>Manteniment:</strong> factures de la revisió anual (oli, bugies, ànodes, filtres) i si s'ha rentat amb aigua dolça després de cada sortida, sobretot el circuit de refrigeració.</li><li><strong>Turbina i impulsor:</strong> cops o desgast per pedres i sorra. Una turbina malmesa es nota en l'acceleració i en vibracions.</li><li><strong>Buc:</strong> cops, esquerdes o reparacions a la part de sota, per varades o pel remolc.</li><li><strong>Motor:</strong> que arrenqui en fred sense problemes i no s'escalfi en marxa. Si porta compressor, pregunta quan es va revisar.</li><li><strong>Remolc:</strong> llums, corrons i que tingui els papers en regla.</li></ul><p>Si la moto s'ho val, una revisió d'un taller de motos d'aigua abans de pagar surt barata comparada amb una avaria. El que és general ho tens a <a href="{P}/guias/que-mirar-comprar-barco-segunda-mano.html">què mirar en comprar de segona mà</a>.</p>
<h2 id="s1">Quina titulació necessites</h2><p>Per governar una moto d'aigua cal titulació: la <strong>Llicència de Navegació</strong> o superior. Amb la Llicència la pots portar de dia i sense allunyar-te més de 2 milles d'un port o lloc d'abric. El PNB també la cobreix, dins dels límits de navegació de la mateixa moto. Ho tens explicat a <a href="{P}/titulaciones/">titulacions</a>.</p><p>A l'estiu, respecta els canals abalisats per sortir i entrar de la platja i les zones de bany: és on més multes es posen.</p>
<h2 id="s2">Papers i el que pagues en comprar</h2><ul><li>Comprova que estigui matriculada a nom del venedor i que no tingui càrregues.</li><li>L'assegurança de responsabilitat civil és obligatòria.</li><li>Si compres a un particular, pagues l'ITP de la teva comunitat (a Catalunya, el 5 %). El tens per comunitats a la <a href="{P}/guias/itp-comprar-barco-usado-por-comunidad.html">guia de l'ITP</a>.</li><li>Després, el canvi de titularitat. T'ho explico a <a href="{P}/guias/papeles-vender-barco-cambio-titularidad.html">papers i canvi de titularitat</a>.</li></ul>
<h2 id="s3">Què influeix en el preu</h2><p>La marca i el model, la potència, l'any, les hores i, sobretot, l'estat i les factures. Una moto de pocs anys amb moltes hores de lloguer pot valer menys que una de més antiga de particular ben cuidada. Si em dius model, any i hores, et dic si un preu està en mercat.</p>
<h2 id="s4">Vens la teva moto d'aigua?</h2><p>Si en tens una i la penses vendre, <a href="{P}/vender-barco/">explica'm què tens</a>. La treballo igual que un vaixell: preu amb criteri, anunci cuidat i atenció als interessats.</p>''',
  'faq': [
   ('Es pot portar una moto d\'aigua sense títol?', 'No. El Reial decret 875/2014 exigeix titulació per governar motos nàutiques: com a mínim, la Llicència de Navegació.'),
   ('Quin títol necessito per a una moto d\'aigua?', 'La Llicència de Navegació o superior. Amb la Llicència, de dia i sense allunyar-te més de 2 milles d\'un port o abric. El PNB també habilita per a motos nàutiques, dins dels seus límits tècnics.'),
   ('Quantes hores són moltes en una moto d\'aigua?', 'Depèn del model i, sobretot, del manteniment. Més que la xifra, mira les factures i quin ús ha tingut: una moto de lloguer sol acumular moltes hores en poc temps.'),
  ],
  'rel': [('{P}/titulaciones/', 'Titulacions nàutiques'), ('{P}/comprar/semirrigidas-neumaticas-segunda-mano.html', 'Semirígides de segona mà'), ('{P}/comprar/cuanto-cuesta-un-barco.html', 'Quant costa un vaixell?'), ('{P}/alertas/', 'Avisa\'m quan n\'entri una')],
 },
 'en': {
  'title': 'Used jet skis for sale in Spain: what to check and licence',
  'desc': 'Pre-owned jet skis (PWC) in Spain: what to check before buying (hours, jet pump, hull, papers), which licence you need and what affects the price.',
  'eyebrow': 'Buy · Jet skis',
  'h1': 'Used jet skis',
  'lead': 'A used jet ski can be a great buy or a headache, and the difference is almost always in what the photos do not show: how it has been used and looked after. Here is what I check before recommending one and the paperwork you need in Spain.',
  'h2list': 'Jet skis for sale',
  'empty': 'Right now I have no jet ski in my listings. <a href="{P}/alertas/">Create an alert</a> and I will let you know as soon as one comes in, before it goes on any portal.',
  'wa': 'Hi Juan, I am looking for a used jet ski.',
  'body': '''<h2 id="s0">What to check before buying</h2><ul><li><strong>Engine hours:</strong> not everything, but they matter. Also ask how it has been used: a private owner's holidays are not the same as a rental fleet.</li><li><strong>Maintenance:</strong> invoices for the yearly service (oil, plugs, anodes, filters) and whether it was flushed with fresh water after every outing, especially the cooling circuit.</li><li><strong>Jet pump and impeller:</strong> damage or wear from stones and sand. A damaged pump shows in acceleration and vibration.</li><li><strong>Hull:</strong> knocks, cracks or repairs underneath, from beaching or the trailer.</li><li><strong>Engine:</strong> it should start cold without trouble and not overheat. If it is supercharged, ask when that was serviced.</li><li><strong>Trailer:</strong> lights, rollers and paperwork in order.</li></ul><p>If the jet ski is worth it, an inspection by a PWC workshop before paying is cheap compared with a breakdown. The general checklist is in <a href="{P}/guias/que-mirar-comprar-barco-segunda-mano.html">what to check when buying used</a>.</p>
<h2 id="s1">Which licence you need</h2><p>In Spain you need a licence to ride a jet ski: the <strong>Licencia de Navegación</strong> or higher. With the Licencia you can ride it in daylight and within 2 miles of a port or shelter. The PNB also covers it, within the jet ski's own limits. See <a href="{P}/titulaciones/">boating licences</a>.</p><p>In summer, use the buoyed lanes to leave and reach the beach and keep clear of swimming areas: that is where most fines are given.</p>
<h2 id="s2">Paperwork and what you pay when buying</h2><ul><li>Check it is registered to the seller and free of charges.</li><li>Third-party liability insurance is compulsory.</li><li>Buying from a private seller, you pay your region's transfer tax (ITP; 5% in Catalonia). See the <a href="{P}/guias/itp-comprar-barco-usado-por-comunidad.html">ITP guide by region</a>.</li><li>Then the change of ownership. More in <a href="{P}/guias/papeles-vender-barco-cambio-titularidad.html">papers and change of ownership</a>.</li></ul>
<h2 id="s3">What affects the price</h2><p>Brand and model, power, year, hours and, above all, condition and invoices. A recent jet ski with many rental hours can be worth less than an older, well-kept private one. Tell me the model, year and hours and I will tell you whether a price is in line with the market.</p>
<h2 id="s4">Selling your jet ski?</h2><p>If you have one and are thinking of selling, <a href="{P}/vender-barco/">tell me about it</a>. I handle it just like a boat: a sensible price, a careful listing and attention to every enquiry.</p>''',
  'faq': [
   ('Can I ride a jet ski in Spain without a licence?', 'No. Royal Decree 875/2014 requires a licence to ride personal watercraft: at least the Licencia de Navegación.'),
   ('Which licence do I need for a jet ski in Spain?', 'The Licencia de Navegación or higher. With the Licencia, in daylight and within 2 miles of a port or shelter. The PNB also covers jet skis, within their technical limits.'),
   ('How many hours is a lot for a jet ski?', 'It depends on the model and, above all, maintenance. Rather than the number, look at the invoices and how it has been used: rental jet skis rack up hours quickly.'),
  ],
  'rel': [('{P}/titulaciones/', 'Boating licences'), ('{P}/comprar/semirrigidas-neumaticas-segunda-mano.html', 'Used RIBs'), ('{P}/comprar/cuanto-cuesta-un-barco.html', 'How much does a boat cost?'), ('{P}/alertas/', 'Alert me when one comes in')],
 },
 'fr': {
  'title': 'Jet-skis d’occasion à vendre en Espagne : quoi vérifier et permis',
  'desc': 'Jet-skis (motos marines) d’occasion en Espagne : quoi vérifier avant d’acheter (heures, turbine, coque, papiers), quel permis et ce qui influe sur le prix.',
  'eyebrow': 'Acheter · Jet-skis',
  'h1': 'Jet-skis d’occasion',
  'lead': 'Un jet-ski d’occasion peut être une belle affaire ou un souci, et la différence se cache presque toujours dans ce que les photos ne montrent pas : comment il a été utilisé et entretenu. Voici ce que je vérifie avant d’en recommander un et les papiers nécessaires en Espagne.',
  'h2list': 'Jet-skis à vendre',
  'empty': 'Pour l’instant, je n’ai aucun jet-ski à vendre. <a href="{P}/alertas/">Créez une alerte</a> et je vous préviendrai dès qu’il en arrive un, avant qu’il ne soit publié sur un portail.',
  'wa': 'Bonjour Juan, je cherche un jet-ski d’occasion.',
  'body': '''<h2 id="s0">Ce qu’il faut vérifier avant d’acheter</h2><ul><li><strong>Heures moteur :</strong> ce n’est pas tout, mais ça compte. Demandez aussi l’usage : un particulier en vacances n’est pas une flotte de location.</li><li><strong>Entretien :</strong> factures de la révision annuelle (huile, bougies, anodes, filtres) et rinçage à l’eau douce après chaque sortie, surtout du circuit de refroidissement.</li><li><strong>Turbine et rotor :</strong> chocs ou usure dus aux pierres et au sable. Une turbine abîmée se sent à l’accélération et par des vibrations.</li><li><strong>Coque :</strong> chocs, fissures ou réparations dessous, dus aux échouages ou à la remorque.</li><li><strong>Moteur :</strong> il doit démarrer à froid sans problème et ne pas chauffer. S’il a un compresseur, demandez quand il a été révisé.</li><li><strong>Remorque :</strong> feux, rouleaux et papiers en règle.</li></ul><p>Si le jet-ski le mérite, un contrôle par un atelier spécialisé avant de payer coûte peu par rapport à une panne. La liste générale est dans <a href="{P}/guias/que-mirar-comprar-barco-segunda-mano.html">ce qu’il faut vérifier en achetant d’occasion</a>.</p>
<h2 id="s1">Quel permis faut-il</h2><p>En Espagne, piloter un jet-ski exige un permis : la <strong>Licencia de Navegación</strong> ou supérieur. Avec la Licencia, de jour et à 2 milles maximum d’un port ou d’un abri. Le PNB le couvre aussi, dans les limites du jet-ski. Si vous avez un permis français, consultez la page <a href="{P}/titulaciones/">permis bateau</a>.</p><p>En été, utilisez les chenaux balisés pour quitter et rejoindre la plage et restez à l’écart des zones de baignade : c’est là que tombent la plupart des amendes.</p>
<h2 id="s2">Papiers et ce que vous payez à l’achat</h2><ul><li>Vérifiez qu’il est immatriculé au nom du vendeur et libre de charges.</li><li>L’assurance responsabilité civile est obligatoire.</li><li>Achat à un particulier : vous payez l’ITP de votre région en Espagne (5 % en Catalogne). Voir le <a href="{P}/guias/itp-comprar-barco-usado-por-comunidad.html">guide de l’ITP par région</a>.</li><li>Si vous comptez l’immatriculer en France, lisez <a href="{P}/guias/comprar-barco-espana-matricular-francia.html">acheter en Espagne et immatriculer en France</a>.</li></ul>
<h2 id="s3">Ce qui influe sur le prix</h2><p>La marque et le modèle, la puissance, l’année, les heures et surtout l’état et les factures. Un jet-ski récent avec beaucoup d’heures de location peut valoir moins qu’un plus ancien bien entretenu par un particulier. Donnez-moi le modèle, l’année et les heures et je vous dirai si un prix est dans le marché.</p>
<h2 id="s4">Vous vendez votre jet-ski ?</h2><p>Si vous en avez un et pensez le vendre, <a href="{P}/vender-barco/">parlez-m’en</a>. Je le traite comme un bateau : un prix réfléchi, une annonce soignée et le suivi de chaque demande.</p>''',
  'faq': [
   ('Peut-on piloter un jet-ski en Espagne sans permis ?', 'Non. Le décret royal 875/2014 exige un titre pour piloter une moto nautique : au minimum la Licencia de Navegación.'),
   ('Quel permis pour un jet-ski en Espagne ?', 'La Licencia de Navegación ou supérieur. Avec la Licencia, de jour et à 2 milles maximum d’un port ou d’un abri. Le PNB couvre aussi les motos nautiques, dans leurs limites techniques.'),
   ('Combien d’heures, c’est beaucoup pour un jet-ski ?', 'Cela dépend du modèle et surtout de l’entretien. Plus que le chiffre, regardez les factures et l’usage : un jet-ski de location accumule vite les heures.'),
  ],
  'rel': [('{P}/titulaciones/', 'Permis bateau'), ('{P}/comprar/semirrigidas-neumaticas-segunda-mano.html', 'Semi-rigides d’occasion'), ('{P}/comprar/cuanto-cuesta-un-barco.html', 'Combien coûte un bateau ?'), ('{P}/alertas/', 'Prévenez-moi')],
 },
}
